package jetbrains.mps.ide.migration;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import java.util.Map;
import org.jetbrains.mps.openapi.module.SModuleReference;
import jetbrains.mps.lang.migration.runtime.base.RefactoringScriptReference;
import java.util.HashMap;
import java.util.List;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.lang.migration.runtime.base.MigrationModuleUtil;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import jetbrains.mps.smodel.Language;
import java.util.ArrayList;
import jetbrains.mps.project.Project;
import jetbrains.mps.lang.migration.runtime.base.RefactoringScript;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.Sequence;

@GeneratedClass(nodeId = "1520098040411279238", model = "a5b1c28d-abeb-49a6-a58c-559039616d64/r:a9597bdf-0806-4a79-8ace-88240c6b9878(jetbrains.mps.migration.component/jetbrains.mps.ide.migration)")
/*package*/ class RefactoringScriptCollector {
  private final Map<SModuleReference, RefactoringScriptReference[]> myModule2Scripts = new HashMap<>();
  private final Map<RefactoringScriptReference, List<SModule>> myGroupedByScript = new HashMap<>();


  /*package*/ RefactoringScriptCollector() {
  }

  /*package*/ void fillFor(SModule module) {
    Map<SModuleReference, Integer> depVersions = MigrationModuleUtil.getRecordedDependencyVersions(module);
    for (SModuleReference dep : SetSequence.fromSet(depVersions.keySet())) {
      RefactoringScriptReference[] scripts = myModule2Scripts.get(dep);
      if (scripts == null) {
        SModule lang = dep.resolve(module.getRepository());
        if (!(lang instanceof Language)) {
          // RefactoringLog lives in language's aspect model, no reason to process modules other than language
          continue;
        }
        int currentDepVersion = ((Language) lang).getModuleVersion();
        currentDepVersion = Math.max(currentDepVersion, 0);
        scripts = new RefactoringScriptReference[currentDepVersion];
        for (int i = 0; i < currentDepVersion; i++) {
          scripts[i] = new RefactoringScriptReference((Language) lang, i);
        }
        myModule2Scripts.put(dep, scripts);
      }
      // record the module for each non-migrated version up to the actual one
      int ver = depVersions.get(dep);

      for (int i = ver; i < scripts.length; i++) {
        myGroupedByScript.computeIfAbsent(scripts[i], (RefactoringScriptReference k) -> new ArrayList<>()).add(module);
      }
    }
  }

  /*package*/ void reportInto(ModuleMigrationSequence mseq, Project mpsProject) {
    for (RefactoringScriptReference sr : SetSequence.fromSet(myGroupedByScript.keySet())) {
      RefactoringScript rs = RefactoringScriptReference.resolve(mpsProject.getRepository(), sr);
      if (rs != null) {
        mseq.record(rs.getReference(), new AppliedRefactoringScript(rs, myGroupedByScript.get(sr)), rs.getExecuteAfter());
      } else {
        // XXX I don't understand the reason to record missing script, it's unlikely there are refactoring scripts at all, why bother
        //    to create RefactoringScriptReference pointing to non-existent scripts?
        mseq.record(sr, new AppliedRefactoringScript(sr, myGroupedByScript.get(sr)), null);
      }
    }
  }

  private static class AppliedRefactoringScript extends AppliedScript {
    /*package*/ AppliedRefactoringScript(RefactoringScriptReference rsr, Iterable<SModule> modules) {
      super(rsr, modules);
    }
    /*package*/ AppliedRefactoringScript(RefactoringScript rs, Iterable<SModule> modules) {
      super(rs, modules);
    }

    @NotNull
    @Override
    public RefactoringScriptReference scriptReference() {
      return (RefactoringScriptReference) super.scriptReference();
    }

    @Override
    public AppliedScript.ApplyState ready(@NotNull SModule module) {
      assert scriptPresent();
      final Map<SModuleReference, Integer> recordedDependencyVersions = MigrationModuleUtil.getRecordedDependencyVersions(module);
      if (recordedDependencyVersions.isEmpty()) {
        // XXX perhaps, another state, like NOTHING TO DO?
        return AppliedScript.ApplyState.ErrorState;
      }
      if (!(recordedDependencyVersions.containsKey(scriptReference().getModuleReference()))) {
        // perhaps, not an error. otoh, if we get that far, there should be a dependency, and missing value means something went wrong
        return AppliedScript.ApplyState.ErrorState;
      }
      int v = recordedDependencyVersions.get(scriptReference().getModuleReference());
      if (v != scriptReference().getFromVersion()) {
        return (v < scriptReference().getFromVersion() ? AppliedScript.ApplyState.ErrorState : AppliedScript.ApplyState.AlreadyMigrated);
      }
      // FIXME quite stupid, imo, extra check if language/module of a RS is part of module dependencies - provided we built
      //      set of modules to migrate *based on actual dependencies*. Shall remove, just keep for 1 commit for historical records.
      if (Sequence.fromIterable(((RefactoringScript) myScript).getExecuteAfter()).where((it) -> recordedDependencyVersions.containsKey(it.getModuleReference())).all((s) -> {
        // containsKey(), above, ensures there's a value in the map

        // Next condition means we got a dependency with a version newer than the one of the script we need to run before, i.e.
        // we assume we depend on a newer version of the module (where script was already present), or the script has been applied already
        // However, with the way we order scripts in ModuleMigrationSequence, we shall see 'true' here always
        return recordedDependencyVersions.get(s.getModuleReference()) > s.getFromVersion();
      })) {
        return AppliedScript.ApplyState.GoodToGo;
      } else {
        return AppliedScript.ApplyState.NeedsDependencies;
      }
    }

    @Override
    public void refreshScriptInstances(Project mpsProject) {
      myScript = RefactoringScriptReference.resolve(mpsProject.getRepository(), scriptReference());
    }
  }
}
