package jetbrains.mps.lang.structure.pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class Structure_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "jetbrains.mps.lang.structure.pluginSolution.plugin.Structure_ActionGroup";
  public static final String LABEL_ID_showHelp = ID + "showHelp";

  public Structure_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("Structure", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    addNamedAnchor(LABEL_ID_showHelp);
  }
}
