<<<<<<< HEAD
#---------------------------------------------------------------------
# In the following sample paths the _VERSION_ placeholder has to be manually
# renamed to reflect the actual version of MPS, for example:
# MPS version is 2023.1 -> replace _VERSION_ with 2023.1
#---------------------------------------------------------------------
=======
# Set up IDEA_PROPERTIES environment variable to specify custom location of this properties file like
# SET IDEA_PROPERTIES=c:\ideaconfig\idea.properties
# before launching idea.
# If not specified it is searched according following sequence (first successful is used).
# 1. ${user.home}
# 2. ${idea.home}/bin

# Use ${idea.home} macro to specify location relative to IDEA installation home
# Also use ${xxx} where xxx is any java property (including defined in previous lines of this file) to refer to its value
# Note for Windows users: please make sure you're using forward slashes. I.e. c:/idea/system

# path to IDEA config folder. Make sure you're using forward slashes
idea.config.path=${user.home}/.MPS15/config

# path to IDEA system folder. Make sure you're using forward slashes
idea.system.path=${user.home}/.MPS15/system

# path to user installed plugins folder. Make sure you're using forward slashes
idea.plugins.path=${user.home}/.MPS15/config/plugins
>>>>>>> origin/MPS1.5

#---------------------------------------------------------------------
# Uncomment this option if you want to customize path to MPS config folder
#---------------------------------------------------------------------
# idea.config.path=${user.home}/.MPS_VERSION_/config

#---------------------------------------------------------------------
# Uncomment this option if you want to customize path to MPS system folder
#---------------------------------------------------------------------
# idea.system.path=${user.home}/.MPS_VERSION_/system

#---------------------------------------------------------------------
# Uncomment this option if you want to customize path to user installed plugins folder
#---------------------------------------------------------------------
# idea.plugins.path=${user.home}/.MPS_VERSION_/config/plugins

#---------------------------------------------------------------------
# Uncomment this option if you want to customize path to MPS logs folder. Make sure you're using forward slashes
#---------------------------------------------------------------------
# idea.log.path=${user.home}/.MPS_VERSION_/system/log


#---------------------------------------------------------------------
# Maximum file size (kilobytes) MPS should provide intellisense for.
# The larger file is the slower its editor works and higher overall system memory requirements are
# if intellisense is enabled. Remove this property or set to very large number if you need
# intellisense for any files available regardless their size.
#---------------------------------------------------------------------
idea.max.intellisense.filesize=100000

# MPS copies library jars to prevent their locking. If copying is not desirable, specify "true"
idea.jars.nocopy=false

# Configure if a special launcher should be used when running processes from within MPS. Using Launcher enables "soft exit" and "thread dump" features
idea.no.launcher=false

# The VM option value to be used start the JVM in debug mode. Some environments define it in a different way (-XXdebug in Oracle VM)
idea.xdebug.key=-Xdebug

#-----------------------------------------------------------------------
# This option controls console cyclic buffer: keeps the console output size not higher than the specified buffer size (Kb). Older lines are deleted.
# In order to disable cycle buffer use idea.cycle.buffer.size=disabled
idea.cycle.buffer.size=1024

#----------------------------------------------------------------------
# Disabling this property may lead to visual glitches like blinking and fail to repaint
# on certain display adapter cards.
#----------------------------------------------------------------------
sun.java2d.noddraw=true

#----------------------------------------------------------------------
# Removing this property may lead to editor performance degradation under Windows.
#----------------------------------------------------------------------
sun.java2d.d3d=false

#----------------------------------------------------------------------
# Removing this property may lead to editor performance degradation under X-Windows.
#----------------------------------------------------------------------
sun.java2d.pmoffscreen=false