#NOTE, this is sample configuration to help craft one for custom debug
# mimics jetbrains.mps.util.LogInitializer logic
handlers=java.util.logging.FileHandler java.util.logging.ConsoleHandler
.level=INFO

# as long as there's no 'millis since start', I decided to put %1$tQ to show millis from the start of epoch,
# although I don't like very big number there. Still, it gives relative distance for two events.
# Another possible format is %3$7s to show caller/source there instead.
java.util.logging.SimpleFormatter.format=%1$tF %1$tT,%1$tL [%1$tQ] %5$6s - %4$30.60s - %6$s%7$s%n

java.util.logging.FileHandler.level=ALL
java.util.logging.FileHandler.append=true
java.util.logging.FileHandler.pattern=idea%g.log
java.util.logging.FileHandler.limit=1048576
java.util.logging.FileHandler.count=12
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

java.util.logging.ConsoleHandler.level=WARNING
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

#these are from log.xml
#unfortunately, it's not possible to redirect certain loggers into separate files with bare JUL
jetbrains.mps.vcs.level=INFO
jetbrains.mps.vcs.useParentHandlers=false
jetbrains.mps.vcs.handler=java.util.logging.FileHandler
com.intellij.openapi.vcs.level=INFO
com.intellij.openapi.vcs.useParentHandlers=false
com.intellij.openapi.vcs.handler=java.util.logging.FileHandler
