package jetbrains.mps.baseLanguage.javastub;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import java.util.function.Function;
import jetbrains.mps.baseLanguage.javastub.asm.ASMClass;
import java.util.zip.ZipFile;
import org.eclipse.jdt.internal.compiler.impl.CompilerOptions;
import java.io.File;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.io.InputStream;
import jetbrains.mps.util.FileUtil;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import org.eclipse.jdt.internal.compiler.batch.CompilationUnit;
import org.eclipse.jdt.internal.compiler.CompilationResult;
import org.eclipse.jdt.internal.compiler.problem.ProblemReporter;
import org.eclipse.jdt.internal.compiler.DefaultErrorHandlingPolicies;
import org.eclipse.jdt.internal.compiler.problem.DefaultProblemFactory;
import org.eclipse.jdt.internal.compiler.parser.Parser;
import org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration;
import org.eclipse.jdt.internal.compiler.ast.Javadoc;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.apache.log4j.Logger;
import java.util.Collections;
import java.util.ArrayList;

@GeneratedClass(node = "r:aa7e8178-3b66-4295-bcce-165c85d78006(jetbrains.mps.baseLanguage.javastub)/8643037841689041893", model = "r:aa7e8178-3b66-4295-bcce-165c85d78006(jetbrains.mps.baseLanguage.javastub)")
public class SingleZipWithJavaSources implements Function<ASMClass, Documentation> {
  private final ZipFile myZipFile;
  private final CompilerOptions myOptions;

  public SingleZipWithJavaSources(File zipFile) throws IOException {
    myZipFile = new ZipFile(zipFile);
    myOptions = new CompilerOptions();
    myOptions.docCommentSupport = true;
    myOptions.ignoreMethodBodies = true;
    myOptions.defaultEncoding = "UTF-8";
    myOptions.complianceLevel = myOptions.originalComplianceLevel = CompilerOptions.versionToJdkLevel(CompilerOptions.VERSION_1_8);
    myOptions.sourceLevel = myOptions.originalSourceLevel = CompilerOptions.versionToJdkLevel(CompilerOptions.VERSION_1_8);
  }

  @Override
  public Documentation apply(ASMClass aClass) {
    ZipEntry entry = myZipFile.getEntry(aClass.getName() + ".java");
    if (entry == null) {
      return null;
    }
    InputStream is = null;
    try {
      is = myZipFile.getInputStream(entry);
      char[] contents = FileUtil.read(new InputStreamReader(is, StandardCharsets.UTF_8)).toCharArray();
      CompilationUnit cu = new CompilationUnit(contents, entry.getName(), myOptions.defaultEncoding, null, true, null);
      CompilationResult cr = new CompilationResult(cu, 0, 0, myOptions.maxProblemsPerUnit);
      ProblemReporter pr = new ProblemReporter(DefaultErrorHandlingPolicies.proceedWithAllProblems(), myOptions, new DefaultProblemFactory());
      Parser p = new Parser(pr, false);
      CompilationUnitDeclaration cud = p.dietParse(cu, cr);
      Javadoc javadoc = (cud.types != null && cud.types.length == 1 ? cud.types[0].javadoc : null);
      if (javadoc != null) {
        List<String> commentLines = linesOf(contents, javadoc.sourceStart, javadoc.sourceEnd);
        if (commentLines.isEmpty()) {
          return null;
        }
        commentLines.toArray(new String[0]);
        final String s = String.join("\n", commentLines.toArray(new String[0]));
        return new Documentation() {
          @Nullable
          @Override
          public String forClassifier() {
            return s;
          }
        };
      }
    } catch (Exception ex) {
      // fine, no documentation for the class 
      Logger.getLogger(SingleZipWithJavaSources.class).debug(String.format("Failed to read/parse source for %s from %s", entry.getName(), myZipFile.getName()), ex);
      return null;
    } finally {
      FileUtil.closeFileSafe(is);
    }
    return null;
  }

  private static List<String> linesOf(char[] contents, int from, int to) {
    final int SLASH = 0;
    final int STAR = 1;
    final int STAR2 = 2;
    final int TEXT = 3;
    // strip head off 
    int state = SLASH;
    for (; from < to; from++) {
      if (state == SLASH) {
        // ignore any character prior to /** 
        if (contents[from] == '/') {
          state = STAR;
        }
        continue;
      }
      if (state == STAR) {
        if (contents[from] != '*') {
          break;
        }
        state = STAR2;
        continue;
      }
      if (state == STAR2) {
        if (contents[from] != '*') {
          break;
        }
        state = TEXT;
        continue;
      }
      if (state == TEXT && contents[from] != '*') {
        break;
      }
    }
    if (state != TEXT) {
      return Collections.<String>emptyList();
    }
    // strip tail off 
    state = SLASH;
    for (; to > from; to--) {
      if (state == SLASH) {
        // ignore any character after */ 
        if (contents[to] == '/') {
          state = STAR;
        }
        continue;
      }
      if (state == STAR) {
        if (contents[to] != '*') {
          break;
        }
        state = TEXT;
        continue;
      }
      if (state == TEXT && contents[to] != '*') {
        break;
      }
    }
    if (state != TEXT || to - from < 2) {
      return Collections.<String>emptyList();
    }
    // ok, now contents[from..to] has leading and trailing javadoc 'brackets' and extra '*' stripped off 
    int lineStart = -1;
    ArrayList<String> rv = new ArrayList<String>(4);
    state = STAR;
    for (; from < to; from++) {
      if (state == STAR) {
        if (Character.isWhitespace(contents[from])) {
          continue;
        }
        if (contents[from] == '*') {
          lineStart = from + 1;
        } else {
          lineStart = from;
        }
        state = TEXT;
        continue;
      }
      if (state == TEXT) {
        if (contents[from] != '\n') {
          continue;
        }
        rv.add(new String(contents, lineStart, from - lineStart));
        state = STAR;
      }
    }
    // in case last line doesn't end up with '\n' 
    if (state == TEXT) {
      rv.add(new String(contents, lineStart, to - lineStart));
    }
    return rv;
  }

}
