package jetbrains.mps.samples.fincalculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ValueKind extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ValueKind() {
    super(0x26b3d6d5b99a4ed6L, 0x83bed2ea6f3627c2L, 0x1d111c815ee9dbb5L, "ValueKind", "r:87765d2d-a756-4883-9acc-6a42e5bf6c24(jetbrains.mps.samples.fincalculator.structure)/2094486643672734645");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_amount_0 = new EnumerationDescriptor.MemberDescriptor("amount", "amount", 0x1d111c815ee9dbb6L, "r:87765d2d-a756-4883-9acc-6a42e5bf6c24(jetbrains.mps.samples.fincalculator.structure)/2094486643672734646");
  private final EnumerationDescriptor.MemberDescriptor myMember_percent_0 = new EnumerationDescriptor.MemberDescriptor("percent", "percent", 0x1d111c815ee9dbb7L, "r:87765d2d-a756-4883-9acc-6a42e5bf6c24(jetbrains.mps.samples.fincalculator.structure)/2094486643672734647");
  private final EnumerationDescriptor.MemberDescriptor myMember_logical_0 = new EnumerationDescriptor.MemberDescriptor("logical", "logical", 0x20e1c9c3baa061c7L, "r:87765d2d-a756-4883-9acc-6a42e5bf6c24(jetbrains.mps.samples.fincalculator.structure)/2369396721460470215");
  private final EnumerationDescriptor.MemberDescriptor myMember_textual_0 = new EnumerationDescriptor.MemberDescriptor("textual", "textual", 0x20e1c9c3baa061ccL, "r:87765d2d-a756-4883-9acc-6a42e5bf6c24(jetbrains.mps.samples.fincalculator.structure)/2369396721460470220");
  private final EnumerationDescriptor.MemberDescriptor myMember_numeric_0 = new EnumerationDescriptor.MemberDescriptor("numeric", "numeric", 0x1d111c815eee70cdL, "r:87765d2d-a756-4883-9acc-6a42e5bf6c24(jetbrains.mps.samples.fincalculator.structure)/2094486643673034957");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x26b3d6d5b99a4ed6L, 0x83bed2ea6f3627c2L, 0x1d111c815ee9dbb5L, 0x1d111c815ee9dbb6L, 0x1d111c815ee9dbb7L, 0x20e1c9c3baa061c7L, 0x20e1c9c3baa061ccL, 0x1d111c815eee70cdL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_amount_0, myMember_percent_0, myMember_logical_0, myMember_textual_0, myMember_numeric_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "amount":
        return myMember_amount_0;
      case "percent":
        return myMember_percent_0;
      case "logical":
        return myMember_logical_0;
      case "textual":
        return myMember_textual_0;
      case "numeric":
        return myMember_numeric_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
