package jetbrains.mps.vcs.changesmanager.tree.features;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNodeReference;

@GeneratedClass(node = "r:eed7a462-d012-4d9f-b223-97987e5d1cb3(jetbrains.mps.vcs.changesmanager.tree.features)/5060092229902868722", model = "r:eed7a462-d012-4d9f-b223-97987e5d1cb3(jetbrains.mps.vcs.changesmanager.tree.features)")
public class ReferencesFeature extends NodeAggregationFeature {
  public ReferencesFeature(@NotNull SNodeReference nodePointer) {
    super(nodePointer);
  }

  @Override
  public int hashCode() {
    return getNodePointer().hashCode() * 23;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj instanceof ReferencesFeature) {
      return getNodePointer().equals(((ReferencesFeature) obj).getNodePointer());
    }
    return false;
  }

  @Override
  @NotNull
  public String toString() {
    return "Node references {" + getNodePointerString() + "}";
  }
}
