package jetbrains.mps.lang.feedback.messages.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ShowMessage_Constraints extends BaseConstraintsDescriptor {
  public ShowMessage_Constraints() {
    super(MetaAdapterFactory.getConcept(0x16e76fe395344defL, 0xafb7925a169a7c0bL, 0x6530303593ae1651L, "jetbrains.mps.lang.feedback.messages.structure.ShowMessage"));
  }

}
