package jetbrains.mps.kotlin.migration;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptBase;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.lang.smodel.query.runtime.CommandUtil;
import jetbrains.mps.project.EditableFilteringScope;
import jetbrains.mps.lang.smodel.query.runtime.QueryExecutionContext;
import jetbrains.mps.internal.collections.runtime.CollectionSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.migration.runtime.base.Problem;
import jetbrains.mps.lang.migration.runtime.base.NotMigratedNode;
import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class MemberNavigationExpression extends MigrationScriptBase {
  private final String description = "Migration 'operand' link in member navigation";
  public String getCaption() {
    return description;
  }
  @Override
  public boolean isRerunnable() {
    return true;
  }
  public SNode execute(final SModule m) {
    doExecute(m);
    return null;
  }
  public void doExecute(final SModule m) {
    {
      SearchScope scope_m6kjbn_a0e = CommandUtil.createScope(m);
      final SearchScope scope_m6kjbn_a0e_0 = new EditableFilteringScope(scope_m6kjbn_a0e);
      QueryExecutionContext context = () -> scope_m6kjbn_a0e_0;
      CollectionSequence.fromCollection(CommandUtil.instances(CommandUtil.selectScope(null, context), CONCEPTS.MemberNavigationExpression$7I, false)).visitAll((it) -> {
        SNode target = SNodeOperations.as(SLinkOperations.getTarget(it, LINKS.operand$YS5t), CONCEPTS.IExpression$2i);
        if (target != null) {
          SLinkOperations.setTarget(it, LINKS.operand$8jSC, target);
        }
      });
    }
  }
  @Override
  public Iterable<Problem> check(SModule m) {
    {
      SearchScope scope_m6kjbn_a0f = CommandUtil.createScope(m);
      final SearchScope scope_m6kjbn_a0f_0 = new EditableFilteringScope(scope_m6kjbn_a0f);
      QueryExecutionContext context = () -> scope_m6kjbn_a0f_0;
      return CollectionSequence.fromCollection(CommandUtil.instances(CommandUtil.selectScope(null, context), CONCEPTS.MemberNavigationExpression$7I, false)).where((it) -> (SNodeOperations.as(SLinkOperations.getTarget(it, LINKS.operand$YS5t), CONCEPTS.IExpression$2i) != null)).select((it) -> {
        return new NotMigratedNode(it) {
          @Override
          public String getMessage() {
            return "deprecated member navigation operand not migrated";
          }
        };
      });
    }
  }
  public MigrationScriptReference getReference() {
    return new MigrationScriptReference(MetaAdapterFactory.getLanguage(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, "jetbrains.mps.kotlin"), 11);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MemberNavigationExpression$7I = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x11400bb790a3792dL, "jetbrains.mps.kotlin.structure.MemberNavigationExpression");
    /*package*/ static final SInterfaceConcept IExpression$2i = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af4d0L, "jetbrains.mps.kotlin.structure.IExpression");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink operand$YS5t = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x11400bb790956f20L, 0x11400bb790956f23L, "operand");
    /*package*/ static final SContainmentLink operand$8jSC = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x11400bb790a3792dL, 0x1db88ba740cf215cL, "operand");
  }
}
