package jetbrains.mps.kotlin.migration;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptBase;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.lang.smodel.query.runtime.CommandUtil;
import jetbrains.mps.project.EditableFilteringScope;
import jetbrains.mps.lang.smodel.query.runtime.QueryExecutionContext;
import jetbrains.mps.internal.collections.runtime.CollectionSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.Objects;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.kotlin.behavior.IVisible__BehaviorDescriptor;
import jetbrains.mps.kotlin.behavior.IConstructorDeclaration__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.kotlin.behavior.IInheritable__BehaviorDescriptor;
import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class OptionalMemberModifiers extends MigrationScriptBase {
  private final String description = "Remove unnecessary public and final modifiers after update";
  public String getCaption() {
    return description;
  }
  @Override
  public boolean isRerunnable() {
    return true;
  }
  public SNode execute(final SModule m) {
    doExecute(m);
    return null;
  }
  public void doExecute(final SModule m) {
    {
      SearchScope scope_ll0a9_a0e = CommandUtil.createScope(m);
      final SearchScope scope_ll0a9_a0e_0 = new EditableFilteringScope(scope_ll0a9_a0e);
      QueryExecutionContext context = () -> scope_ll0a9_a0e_0;
      CollectionSequence.fromCollection(CommandUtil.instances(CommandUtil.selectScope(null, context), CONCEPTS.IVisible$LZ, false)).where((it) -> {
        if ((SLinkOperations.getTarget(it, LINKS.visibility$vnSV) != null) && Objects.equals(SNodeOperations.getConcept(SLinkOperations.getTarget(it, LINKS.visibility$vnSV)), IVisible__BehaviorDescriptor.getDefaultVisibility_id2WVyZr43qIN.invoke(it))) {
          return true;
        }

        // One specific case: constructor of sealed and enum classes
        {
          final SNode constructor = it;
          if (SNodeOperations.isInstanceOf(constructor, CONCEPTS.IConstructorDeclaration$rR)) {
            SNode constructedClass = IConstructorDeclaration__BehaviorDescriptor.getConstructedClass_id7WpE6U5evQG.invoke(constructor);

            if (SNodeOperations.isInstanceOf(constructedClass, CONCEPTS.EnumClassDeclaration$xK) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, LINKS.visibility$vnSV), CONCEPTS.PublicVisibility$Me)) {
              return true;
            }

            if (SConceptOperations.isExactly(SNodeOperations.asSConcept(IInheritable__BehaviorDescriptor.getInheritance_id6jE_6duswG9.invoke(constructedClass)), CONCEPTS.SealedInheritanceModifier$vk) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, LINKS.visibility$vnSV), CONCEPTS.PublicVisibility$Me)) {
              return true;
            }
          }
        }
        return false;
      }).visitAll((it) -> SNodeOperations.deleteNode(SLinkOperations.getTarget(it, LINKS.visibility$vnSV)));

      CollectionSequence.fromCollection(CommandUtil.instances(CommandUtil.selectScope(null, context), CONCEPTS.IInheritable$pc, false)).where((it) -> (SLinkOperations.getTarget(it, LINKS.inheritance$TFvr) != null) && Objects.equals(SNodeOperations.getConcept(SLinkOperations.getTarget(it, LINKS.inheritance$TFvr)), IInheritable__BehaviorDescriptor.getDefaultInheritance_id6jE_6dusz0P.invoke(it))).visitAll((it) -> SNodeOperations.deleteNode(SLinkOperations.getTarget(it, LINKS.inheritance$TFvr)));

    }
  }
  public MigrationScriptReference getReference() {
    return new MigrationScriptReference(MetaAdapterFactory.getLanguage(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, "jetbrains.mps.kotlin"), 10);
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IVisible$LZ = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x631027d1c4c4e03fL, "jetbrains.mps.kotlin.structure.IVisible");
    /*package*/ static final SInterfaceConcept IConstructorDeclaration$rR = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x7069a625f2b0238aL, "jetbrains.mps.kotlin.structure.IConstructorDeclaration");
    /*package*/ static final SConcept PublicVisibility$Me = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af395L, "jetbrains.mps.kotlin.structure.PublicVisibility");
    /*package*/ static final SConcept EnumClassDeclaration$xK = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d75547b5aaL, "jetbrains.mps.kotlin.structure.EnumClassDeclaration");
    /*package*/ static final SConcept SealedInheritanceModifier$vk = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af408L, "jetbrains.mps.kotlin.structure.SealedInheritanceModifier");
    /*package*/ static final SInterfaceConcept IInheritable$pc = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x537372687dd3bcdaL, "jetbrains.mps.kotlin.structure.IInheritable");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink visibility$vnSV = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x631027d1c4c4e03fL, 0x631027d1c4c4e040L, "visibility");
    /*package*/ static final SContainmentLink inheritance$TFvr = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x537372687dd3bcdaL, 0x537372687dd3bcdbL, "inheritance");
  }
}
