package jetbrains.mps.lang.text.pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;

public final class MacOSX105_KeymapChanges extends BaseKeymapChanges {
  public MacOSX105_KeymapChanges() {
    replace("jetbrains.mps.lang.text.pluginSolution.plugin.TurnBold_Action", "ctrl B");
    replace("jetbrains.mps.lang.text.pluginSolution.plugin.TurnItalics_Action", "ctrl I");
    replace("jetbrains.mps.lang.text.pluginSolution.plugin.TurnUnderlined_Action", "ctrl U");
  }
  @Override
  public String getScheme() {
    return "Mac OS X 10.5+";
  }

}
