package jetbrains.mps.kotlin.smodel.generator.util;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.Objects;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;

public class ConceptTypeContext {
  public static boolean shouldDowncast(SNode typeNode) {
    return !(Objects.equals(SNodeOperations.getContainingLink(typeNode), LINKS.type$NVFj));
  }

  public static boolean isConceptType(SNode conceptType) {
    if (SNodeOperations.isInstanceOf(conceptType, CONCEPTS.IConceptType$FD)) {
      return true;
    }
    {
      final SNode ref = conceptType;
      if (SNodeOperations.isInstanceOf(ref, CONCEPTS.TypeParameterReference$ya)) {
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ref, LINKS.parameter$ofYr), CONCEPTS.ConceptTypeParameter$8S)) {
          return true;
        }

        // TODO check bounds otherwise?
      }
    }

    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink type$NVFj = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af541L, 0x28bef6d7551af8c0L, "type");
    /*package*/ static final SReferenceLink parameter$ofYr = MetaAdapterFactory.getReferenceLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x21e0c9232886358dL, 0x21e0c9232886358eL, "parameter");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IConceptType$FD = MetaAdapterFactory.getInterfaceConcept(0xeb56ebf4df56438eL, 0xaf06fc1cd08b495aL, 0x22287f289569c889L, "jetbrains.mps.kotlin.smodel.structure.IConceptType");
    /*package*/ static final SConcept TypeParameterReference$ya = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x21e0c9232886358dL, "jetbrains.mps.kotlin.structure.TypeParameterReference");
    /*package*/ static final SConcept ConceptTypeParameter$8S = MetaAdapterFactory.getConcept(0xeb56ebf4df56438eL, 0xaf06fc1cd08b495aL, 0x4da39967d12f7142L, "jetbrains.mps.kotlin.smodel.structure.ConceptTypeParameter");
  }
}
