package jetbrains.mps.baseLanguage.methodReferences.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class MethodReferenceType_SubstituteMenu extends SubstituteMenuBase {
  public MethodReferenceType_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "MethodReferenceType", new SNodePointer("r:4cdf4bee-5b50-4ccb-8bec-50fada7c094a(jetbrains.mps.baseLanguage.methodReferences.editor)", "3748798472489545274")));
  }

}
