package jetbrains.mps.lang.refactoring.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;
import com.intellij.ui.ExperimentalUI;

public class IconContainer {
  protected static IconResource RESOURCE_a0a4a0a53b0xb = (ExperimentalUI.isNewUI() ? new IconResource("refactoring_newui.svg", IconContainer.class) : new IconResource("refactoring.png", IconContainer.class));
}
