package jetbrains.mps.lang.dataFlow.framework;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import java.util.Collection;
import org.jetbrains.annotations.NotNull;

/**
 * @author simon
 */
@GeneratedClass(node = "r:3dddb2c7-b2ba-4381-896a-2e702ca1fb6e(jetbrains.mps.lang.dataFlow.framework)/4074113095384034111", model = "r:3dddb2c7-b2ba-4381-896a-2e702ca1fb6e(jetbrains.mps.lang.dataFlow.framework)")
public class ProgramBuilderContextImpl implements ProgramBuilderContext {
  private Collection<IDataFlowModeId> myBuilderModes;
  public ProgramBuilderContextImpl(@NotNull Collection<IDataFlowModeId> builderModes) {
    myBuilderModes = builderModes;
  }
  @Override
  public Collection<IDataFlowModeId> getBuilderModes() {
    return myBuilderModes;
  }
}
