package jetbrains.mps.baseLanguage.unitTest.execution.tool;

/*Generated by MPS */

import org.jetbrains.annotations.NotNull;
import jetbrains.mps.baseLanguage.unitTest.execution.client.TestRunState;
import org.jetbrains.annotations.Nullable;

public class MPSRootTestProxy extends BaseMPSTestProxy {
  private final RootTestTreeNode myTreeNode;

  public MPSRootTestProxy(@NotNull RootTestTreeNode treeNode, @NotNull TestRunState runState) {
    super(runState);
    myTreeNode = treeNode;
  }

  @Override
  public String getName() {
    return "<ROOT>";
  }

  @Nullable
  @Override
  public String getLocationUrl() {
    return "<ROOT>";
  }


  @Override
  protected TestState getState() {
    return myTreeNode.getState();
  }
}
