package jetbrains.mps.ide.mpsmigration.v_2019_1;

/*Generated by MPS */

import jetbrains.mps.migration.global.BaseProjectMigration;
import jetbrains.mps.logging.Logger;
import jetbrains.mps.project.Project;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.lang.smodel.query.runtime.CommandUtil;
import jetbrains.mps.project.EditableFilteringScope;
import jetbrains.mps.lang.smodel.query.runtime.QueryExecutionContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.project.AbstractModule;
import jetbrains.mps.smodel.Generator;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SReference;
import jetbrains.mps.smodel.StaticReference;
import jetbrains.mps.smodel.SModelStereotype;
import org.jetbrains.mps.openapi.model.EditableSModel;

public class UpdateJavaStubMethodRefs extends BaseProjectMigration {
  private static final Logger LOG = Logger.getLogger(UpdateJavaStubMethodRefs.class);
  public UpdateJavaStubMethodRefs() {
    super("jetbrains.mps.ide.mpsmigration.v191." + UpdateJavaStubMethodRefs.class.getSimpleName(), 191);
  }

  @Override
  public boolean doExecute(Project project) {
    {
      SearchScope scope_2py47h_a0c = CommandUtil.createScope(project);
      final SearchScope scope_2py47h_a0c_0 = new EditableFilteringScope(scope_2py47h_a0c);
      final QueryExecutionContext context = () -> scope_2py47h_a0c_0;
      project.getRepository().getModelAccess().runReadAction(() -> {
        Sequence.fromIterable(CommandUtil.modules(CommandUtil.selectScope(null, context))).visitAll((it) -> {
          if (it instanceof AbstractModule) {
            AbstractModule module = (AbstractModule) it;
            module.updateExternalReferences();
            if (!(module instanceof Generator)) {
              // generators are saved as part of owning Language's save, no need to do it twice
              module.save();
            }
          }
        });
        Sequence.fromIterable(CommandUtil.references(CommandUtil.selectScope(null, context))).where((it) -> {
          SNode targetNode = it.getTargetNode();
          if (targetNode == null) {
            // broken?
            return false;
          }
          return ((SReference) it) instanceof StaticReference && SModelStereotype.isStubModel(targetNode.getModel());
        }).visitAll((it) -> {
          StaticReference reference = (StaticReference) ((SReference) it);
          reference.setTargetNodeId((reference.getTargetNode()).getNodeId());
        });
        Sequence.fromIterable(CommandUtil.models(CommandUtil.selectScope(null, context))).where((it) -> !(SModelStereotype.isStubModel(it)) && it instanceof EditableSModel).where((it) -> !(((EditableSModel) it).isReadOnly())).visitAll((it) -> {
          EditableSModel model = (EditableSModel) it;
          try {
            // ensure model is loaded
            model.load();
            // and force to save model
            model.setChanged(true);
            if (model.isChanged()) {
              model.save();
            }
          } catch (Exception ex) {
            if (LOG.isErrorLevel()) {
              LOG.error("Error re-saving model " + model.getName(), ex);
            }
          }
        });
      });
    }
    return true;
  }

  @Override
  public String getDescription() {
    return "Update all java stub method references in the project";
  }
}
