package jetbrains.mps.baseLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SConcept;

public final class IForEachLoop__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getInterfaceConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x438cca3007b7857bL, "jetbrains.mps.baseLanguage.structure.IForEachLoop");

  public static final SMethod<SNode> inputSequence_id4ecMz07HSmN = new SMethodBuilder<>(SNode.class).name("inputSequence").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4867487604917372339L).languageId(0xa443f952ceaf5816L, 0xf3061a5392264cc5L).build2();
  public static final SMethod<SNode> loopVariableDeclaration_id4ecMz07HX68 = new SMethodBuilder<>(SNode.class).name("loopVariableDeclaration").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4867487604917391752L).languageId(0xa443f952ceaf5816L, 0xf3061a5392264cc5L).build2();
  public static final SMethod<SNode> loopVariableType_id4ecMz07HYZb = new SMethodBuilder<>(SNode.class).name("loopVariableType").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4867487604917399499L).languageId(0xa443f952ceaf5816L, 0xf3061a5392264cc5L).build2();

  private final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(inputSequence_id4ecMz07HSmN, loopVariableDeclaration_id4ecMz07HX68, loopVariableType_id4ecMz07HYZb);


  /*package*/ static SNode inputSequence_id4ecMz07HSmN(@NotNull SNode __thisNode__) {
    return null;
  }
  /*package*/ static SNode loopVariableDeclaration_id4ecMz07HX68(@NotNull SNode __thisNode__) {
    return null;
  }
  /*package*/ static SNode loopVariableType_id4ecMz07HYZb(@NotNull SNode __thisNode__) {
    return SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(IForEachLoop__BehaviorDescriptor.loopVariableDeclaration_id4ecMz07HX68.invoke(__thisNode__)), CONCEPTS.Type$bu);
  }

  /*package*/ IForEachLoop__BehaviorDescriptor() {
  }


  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((SNode) inputSequence_id4ecMz07HSmN(node));
      case 1:
        return (T) ((SNode) loopVariableDeclaration_id4ecMz07HX68(node));
      case 2:
        return (T) ((SNode) loopVariableType_id4ecMz07HYZb(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Type$bu = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506dL, "jetbrains.mps.baseLanguage.structure.Type");
  }
}
