package jetbrains.mps.lang.doctext.util;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.TemplateQueryContext;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.extapi.module.TransientSModule;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.project.facets.DocumentationFacet;
import jetbrains.mps.vfs.IFile;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.baseLanguage.logging.rt.LogContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class DocumentationPathResolver {
  public static String getDocumentationLocation(SNode node, TemplateQueryContext genContext) {
    SModel model = SNodeOperations.getModel(node);
    if (model.getModule() instanceof TransientSModule) {
      model = genContext.getOriginalInputModel();
    }
    SModule module = model.getModule();
    DocumentationFacet docFacet = module.getFacet(DocumentationFacet.class);
    if (docFacet == null) {
      return null;
    }
    IFile folder = docFacet.getLocation();
    return folder.getPath();
  }

  public static String getDocFileNameWithoutExtension(SNode node) throws IllegalArgumentException {
    if (SNodeOperations.isInstanceOf(node, CONCEPTS.AbstractConceptDeclaration$KA)) {
      return SPropertyOperations.getString(SNodeOperations.as(node, CONCEPTS.AbstractConceptDeclaration$KA), PROPS.conceptId$rrGe) + "_AConcept";
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.ConstrainedDataTypeDeclaration$Ch)) {
      return SPropertyOperations.getString(SNodeOperations.as(node, CONCEPTS.ConstrainedDataTypeDeclaration$Ch), PROPS.datatypeId$$gBg) + "_ConstrainedDataType";
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.EnumerationDeclaration$hv)) {
      return SPropertyOperations.getString(SNodeOperations.as(node, CONCEPTS.EnumerationDeclaration$hv), PROPS.datatypeId$$gBg) + "_Enum";
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.PrimitiveDataTypeDeclaration$80)) {
      return SPropertyOperations.getString(SNodeOperations.as(node, CONCEPTS.PrimitiveDataTypeDeclaration$80), PROPS.datatypeId$$gBg) + "_PrimitiveDataType";
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.ConceptEditorDeclaration$BH)) {
      return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.as(node, CONCEPTS.ConceptEditorDeclaration$BH), LINKS.conceptDeclaration$HJmJ), PROPS.conceptId$rrGe) + "_Editor";
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.EditorComponentDeclaration$WM)) {
      return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.as(node, CONCEPTS.EditorComponentDeclaration$WM), LINKS.conceptDeclaration$HJmJ), PROPS.conceptId$rrGe) + "_EditorComponent";
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.ConceptBehavior$2)) {
      return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.as(node, CONCEPTS.ConceptBehavior$2), LINKS.concept$u6dL), PROPS.conceptId$rrGe) + "_Behavior";
    }
    LogContext.with(DocumentationPathResolver.class, null, null, null).error("File name for concept " + node + "cannot be evaluated.");
    return "File name for concept " + node + "cannot be evaluated.";
  }

  public static String getDocFileNameWithExtension(SNode node) throws IllegalArgumentException {
    return getDocFileNameWithoutExtension(node) + ".html";
  }


  public static String getModulePath(SNode node, TemplateQueryContext genContext) {
    SModel model = SNodeOperations.getModel(node);
    if (model.getModule() instanceof TransientSModule) {
      model = genContext.getOriginalInputModel();
    }
    return SModelOperations.getModelName(model).replace('.', '/');
  }

  public static String getDocPath(SNode node, TemplateQueryContext genContext) {
    if (!(DocumentationPathResolver.docExists(node, genContext))) {
      return null;
    }
    String targetModulePath = DocumentationPathResolver.getModulePath(node, genContext);
    String targetFileName = DocumentationPathResolver.getDocFileNameWithExtension(node);
    SNode sourceNode = genContext.getOriginalCopiedInputNode(node);
    String sourceModulePath = DocumentationPathResolver.getModulePath(sourceNode, genContext);
    return DocumentationPathResolver.computeRelativePath(sourceModulePath, targetModulePath, targetFileName);
  }

  private static String computeRelativePath(String fromDir, String toDir, String toFile) {
    String[] from = fromDir.split("/");
    String[] to = toDir.split("/");
    int common = 0;
    while (common < from.length && common < to.length && from[common].equals(to[common])) {
      common++;
    }
    StringBuilder rel = new StringBuilder();
    for (int i = common; i < from.length; i++) {
      rel.append("../");
    }
    for (int i = common; i < to.length; i++) {
      rel.append(to[i]).append("/");
    }
    rel.append(toFile);
    return rel.toString();
  }

  public static boolean docExists(SNode node, TemplateQueryContext genContext) {
    SModel model = SNodeOperations.getModel(node);
    if (model.getModule() instanceof TransientSModule) {
      model = genContext.getOriginalInputModel();
    }
    SModule module = model.getModule();
    DocumentationFacet docFacet = module.getFacet(DocumentationFacet.class);
    return docFacet != null;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractConceptDeclaration$KA = MetaAdapterFactory.getConcept(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, "jetbrains.mps.lang.structure.structure.AbstractConceptDeclaration");
    /*package*/ static final SConcept ConstrainedDataTypeDeclaration$Ch = MetaAdapterFactory.getConcept(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xfc268c7a37L, "jetbrains.mps.lang.structure.structure.ConstrainedDataTypeDeclaration");
    /*package*/ static final SConcept EnumerationDeclaration$hv = MetaAdapterFactory.getConcept(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x2e770ca32c607c5fL, "jetbrains.mps.lang.structure.structure.EnumerationDeclaration");
    /*package*/ static final SConcept PrimitiveDataTypeDeclaration$80 = MetaAdapterFactory.getConcept(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xfc3652de27L, "jetbrains.mps.lang.structure.structure.PrimitiveDataTypeDeclaration");
    /*package*/ static final SConcept ConceptEditorDeclaration$BH = MetaAdapterFactory.getConcept(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xf9845363abL, "jetbrains.mps.lang.editor.structure.ConceptEditorDeclaration");
    /*package*/ static final SConcept EditorComponentDeclaration$WM = MetaAdapterFactory.getConcept(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfb35c2bb47L, "jetbrains.mps.lang.editor.structure.EditorComponentDeclaration");
    /*package*/ static final SConcept ConceptBehavior$2 = MetaAdapterFactory.getConcept(0xaf65afd8f0dd4942L, 0x87d963a55f2a9db1L, 0x11d43447b1aL, "jetbrains.mps.lang.behavior.structure.ConceptBehavior");
  }

  private static final class PROPS {
    /*package*/ static final SProperty conceptId$rrGe = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, 0x5d2e6079771f8cc0L, "conceptId");
    /*package*/ static final SProperty datatypeId$$gBg = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xfc26875dfaL, 0x6c1f946a87044403L, "datatypeId");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink conceptDeclaration$HJmJ = MetaAdapterFactory.getReferenceLink(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x10f7df344a9L, 0x10f7df451aeL, "conceptDeclaration");
    /*package*/ static final SReferenceLink concept$u6dL = MetaAdapterFactory.getReferenceLink(0xaf65afd8f0dd4942L, 0x87d963a55f2a9db1L, 0x11d43447b1aL, 0x11d43447b1fL, "concept");
  }
}
