package jetbrains.mps.kotlin.scopes;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.kotlin.behavior.IClassLike__BehaviorDescriptor;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.kotlin.stubs.platform.TargetPlatform;
import jetbrains.mps.kotlin.behavior.IKotlinRoot__BehaviorDescriptor;
import jetbrains.mps.scope.FilteringScope;
import jetbrains.mps.scope.ModelsScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.kotlin.behavior.PlatformHelper;
import jetbrains.mps.kotlin.scopes.signed.TopLevelVisibility;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class ClassScopeHelper {
  /**
   * 
   * @deprecated integrated in IClassLike scope logic
   */
  @Deprecated(since = "2023.1")
  public static boolean hasAccessToInstanceScopeOf(SNode child, SNode parentClass) {
    SNode ancestor = SNodeOperations.getNodeAncestor(child, CONCEPTS.IClassLike$go, true, false);
    if (ancestor == null) {
      return false;
    }
    if (ancestor == parentClass) {
      return true;
    }
    if ((boolean) IClassLike__BehaviorDescriptor.hasModifier_id2NtWm0y2Y2A.invoke(ancestor, CONCEPTS.InnerClassModifier$wL)) {
      // To prevent infinite recursion
      SNode childToUse = (ancestor == child ? SNodeOperations.getParent(child) : ancestor);
      return hasAccessToInstanceScopeOf(childToUse, parentClass);
    }
    return false;
  }

  public static Scope create(final SNode contextNode) {
    TargetPlatform platform = IKotlinRoot__BehaviorDescriptor.getPlatform_id2Gpd$BYJrkg.invoke(SNodeOperations.asSConcept(CONCEPTS.IKotlinRoot$xV), contextNode);

    return new FilteringScope(new ModelsScope(Sequence.fromStream(PlatformHelper.compatibleImportedModels(contextNode, platform)), false, CONCEPTS.IClassLike$go)) {
      @Override
      public boolean isExcluded(SNode node) {
        // Only objects and classes, and filter out visibility
        return (!(SNodeOperations.isInstanceOf(node, CONCEPTS.IClassDeclaration$bQ)) && !(SNodeOperations.isInstanceOf(node, CONCEPTS.IObject$38))) || !(TopLevelVisibility.visibleTo(node, contextNode));
      }
    };
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IClassLike$go = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x298a6a355c110274L, "jetbrains.mps.kotlin.structure.IClassLike");
    /*package*/ static final SConcept InnerClassModifier$wL = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af40bL, "jetbrains.mps.kotlin.structure.InnerClassModifier");
    /*package*/ static final SInterfaceConcept IKotlinRoot$xV = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x713f27d92240e539L, "jetbrains.mps.kotlin.structure.IKotlinRoot");
    /*package*/ static final SInterfaceConcept IClassDeclaration$bQ = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d75547b56dL, "jetbrains.mps.kotlin.structure.IClassDeclaration");
    /*package*/ static final SInterfaceConcept IObject$38 = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x1ba36e493d40fea4L, "jetbrains.mps.kotlin.structure.IObject");
  }
}
