package jetbrains.mps.lang.migration.runtime.base;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.project.Project;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.project.DevKit;
import jetbrains.mps.smodel.tempmodel.TempModule;
import jetbrains.mps.smodel.tempmodel.TempModule2;
import java.util.Map;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.project.AbstractModule;
import jetbrains.mps.project.structure.modules.ModuleDescriptor;
import java.util.Collections;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.internal.collections.runtime.SetSequence;

@GeneratedClass(nodeId = "5464540062512236006", model = "528ff3b9-5fc4-40dd-931f-c6ce3650640e/r:f69c3fa1-0e30-4980-84e2-190ae44e4c3d(jetbrains.mps.lang.migration.runtime/jetbrains.mps.lang.migration.runtime.base)")
public class MigrationModuleUtil {
  public static Iterable<SModule> getMigrateableModulesFromProject(Project p) {
    Iterable<SModule> modules = p.getProjectModulesWithGenerators();
    return Sequence.fromIterable(modules).where((it) -> isModuleMigrateable(it));
  }

  public static boolean isModuleMigrateable(SModule m) {
    return !(m.isReadOnly()) && MigrationModuleUtil.wouldBeMigrateableWhenNotPacked(m);
  }

  public static boolean wouldBeMigrateableWhenNotPacked(SModule m) {
    return !(m instanceof DevKit) && !(m instanceof TempModule || m instanceof TempModule2);
  }

  /**
   * State of all module dependencies the moment they were recorded for a module
   */
  public static Map<SModuleReference, Integer> getRecordedDependencyVersions(@NotNull SModule module) {
    if (module instanceof AbstractModule) {
      ModuleDescriptor md = ((AbstractModule) module).getModuleDescriptor();
      if (md != null) {
        return md.getDependencyVersions();
      }
      // fall through
    }
    return Collections.emptyMap();
  }

  /**
   * State of all used languages and their prerequisites (e.g. extended languages not used explicitly) as recorded for a module
   */
  public static Map<SLanguage, Integer> getRecordedUsedLanguageVersions(@NotNull SModule module) {
    if (module instanceof AbstractModule) {
      ModuleDescriptor md = ((AbstractModule) module).getModuleDescriptor();
      if (md != null) {
        return md.getLanguageVersions();
      }
      // fall through
    }
    return Collections.emptyMap();
  }
  /**
   * Update version of a used language in the module's state
   */
  public static void recordUsedLanguageVersion(@NotNull SModule module, @NotNull SLanguage usedLang, int version) {
    if (module instanceof AbstractModule) {
      ((AbstractModule) module).getModuleDescriptor().getLanguageVersions().put(usedLang, version);
    } else {
      throw new IllegalArgumentException("We are able to work only with AbstractModule instances");
    }
  }

  /**
   * Update version of a dependency in the module's state
   */
  public static void recordDependencyVersion(SModule module, SModuleReference dependency, int version) {
    ModuleDescriptor moduleDescriptor = ((AbstractModule) module).getModuleDescriptor();
    if (moduleDescriptor == null) {
      throw new IllegalArgumentException();
    }
    moduleDescriptor.getDependencyVersions().put(dependency, version);
    ((AbstractModule) module).setChanged();
  }

  public static boolean allRecordedDependenciesActual(SModule module) {
    final Map<SModuleReference, Integer> depVersions = getRecordedDependencyVersions(module);
    for (SModuleReference dep : SetSequence.fromSet(depVersions.keySet())) {
      SModule am = dep.resolve(module.getRepository());
      if (am == null) {
        // in fact, it's not exactly "outdated" dependency, rather "broken", but for refactoring logs, a legacy functionality, doesn't make sense to fight for better reporting
        return false;
      }
      if (am instanceof AbstractModule) {
        // XXX provided refactoring scripts reside in Language modules only, and single use of the method in refactoring log participant, perhaps, could limit even further
        //    to instanceof Language. However, method name doesn't reflect this, check every dependency
        int currentVersion = ((AbstractModule) am).getModuleVersion();
        int recordedVer = depVersions.get(dep);
        if (recordedVer != currentVersion) {
          return false;
        }
      }
      // silently skip !AM, they are of no interest for us
    }
    return true;
  }
}
