package jetbrains.mps.kotlin.runtime.members;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.kotlin.runtime.members.signature.MemberSignature;
import jetbrains.mps.kotlin.runtime.declaration.FunctionDeclaration;

public abstract class SourcedFunctionSignature extends SourcedSignature {
  public SourcedFunctionSignature(SNode source, MemberSignature signature) {
    super(source, signature);
  }

  public abstract FunctionDeclaration getDescriptor();
}
