package jetbrains.mps.generator.extensions;

/*Generated by MPS */

import jetbrains.mps.generator.plan.PlanParameterContributor;
import jetbrains.mps.generator.plan.PlanParameterIdentity;
import jetbrains.mps.generator.impl.plan.TrivialParameterIdentity;
import java.util.stream.Stream;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SModuleFacet;

public class ModuleFacetPlanParameterContributor implements PlanParameterContributor {

  private final PlanParameterIdentity myFacetParam = new TrivialParameterIdentity("jetbrains.mps.generator.extensions.module-facet");

  @Override
  public Stream<PlanParameterIdentity> parameters() {
    return Stream.<PlanParameterIdentity>of(myFacetParam);
  }
  @Override
  public void contributeParameters(@NotNull PlanParameterContributor.Context context) {
    SModule module = context.model().getModule();
    for (SModuleFacet f : module.getFacets()) {
      context.put(myFacetParam, f.getFacetType());
    }
  }
}
