package jetbrains.mps.idea.java;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Constants {
  public static final SLanguage baseLanguage = MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  public static final SLanguage baseLanguageJavadoc = MetaAdapterFactory.getLanguage(0xf280165065d5424eL, 0xbb1b463a8781b786L, "jetbrains.mps.baseLanguage.javadoc");

  public static class ConceptNames {
    public static final String Classifier = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String ClassConcept = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String Interface = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String EnumClass = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;

    public static final String ClassifierType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String StringType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String PrimitiveType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String UpperBoundType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String LowerBoundType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String WildCardType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String ArrayType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String VariableArityType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;

    public static final String ConstructorDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String BaseMethodDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String MethodDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String ParameterDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String VariableDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String TypeVariableDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String TypeVariableReference = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String FieldDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String EnumConstantDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String StaticFieldDeclaration = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;

    public static final String SequenceType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String ListType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String SetType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;
    public static final String MapType = <!TextGen not found for 'jetbrains.mps.lang.smodel.structure.ConceptFqNameRefExpression'!>;


  }

}
