package jetbrains.mps.ide.depanalyzer.actions;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class ContributeToAnalyzeModule_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "jetbrains.mps.ide.depanalyzer.actions.ContributeToAnalyzeModule_ActionGroup";

  public ContributeToAnalyzeModule_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("ContributeToAnalyzeModule", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    ContributeToAnalyzeModule_ActionGroup.this.addAction("jetbrains.mps.ide.depanalyzer.actions.AnalyzeModuleDependencies_Action");
  }
}
