package jetbrains.mps.kotlin.baseLanguage.typeConversion;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.List;
import jetbrains.mps.references.Reference;
import java.util.ArrayList;
import java.util.ListIterator;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class TypeConverterEngine<S extends SNode, R extends SNode> {
  private HashMap<SAbstractConcept, List<TypeConverter<S, R>>> myConverters;
  private HashMap<SAbstractConcept, List<TypeConverter<S, R>>> getConverters() {
    return this.myConverters;
  }
  private void _setConverters(HashMap<SAbstractConcept, List<TypeConverter<S, R>>> value) {
    this.myConverters = value;
  }
  private HashMap<SAbstractConcept, List<TypeConverter<S, R>>> setConverters(HashMap<SAbstractConcept, List<TypeConverter<S, R>>> value) {
    _setConverters(value);
    return value;
  }
  private Reference<HashMap<SAbstractConcept, List<TypeConverter<S, R>>>> refToConverters() {
    return new Reference<HashMap<SAbstractConcept, List<TypeConverter<S, R>>>>() {
      public HashMap<SAbstractConcept, List<TypeConverter<S, R>>> get() {
        return getConverters();
      }
      public void set(HashMap<SAbstractConcept, List<TypeConverter<S, R>>> value) {
        _setConverters(value);
      }
    };
  }

  public TypeConverterEngine() {
    setConverters(new HashMap<>());
  }

  public ConverterRegistration declareMapping(SAbstractConcept sourceConcept, TypeConverter<S, R> converter) {
    return declareMappingGeneric(getConverters(), sourceConcept, converter);
  }

  protected <T> ConverterRegistration declareMappingGeneric(HashMap<T, List<TypeConverter<S, R>>> map, T key, TypeConverter<S, R> converter) {
    if (!(map.containsKey(key))) {
      // ArrayList as insertion only occur at initialization, most of the processing will require iterating
      ArrayList<TypeConverter<S, R>> list = new ArrayList<>();
      list.add(converter);
      map.put(key, list);
    } else {
      ListIterator<TypeConverter<S, R>> listIterator = map.get(key).listIterator();
      while (listIterator.hasNext() && listIterator.next().getPriority() > converter.getPriority()) {
        // continue
      }
      listIterator.add(converter);
    }

    return new ConverterRegistration(key, converter);
  }

  public void unregister(ConverterRegistration registration) {
    if (registration != null && registration.key instanceof SAbstractConcept) {
      List<TypeConverter<S, R>> list = getConverters().get(registration.key);
      list.remove(registration.converter);
    }
  }

  public R convert(S sourceNode) {
    return convert(SNodeOperations.getConcept(sourceNode), sourceNode);
  }

  /**
   * Convert node assuming it is of the given concept.
   * 
   * Used internally to find matches to superconcepts.
   */
  public R convert(SAbstractConcept concept, S sourceNode) {
    R res = convert(concept, sourceNode, getConverters().get(concept));
    if (res != null) {
      return res;
    }

    for (SAbstractConcept superconcept : ListSequence.fromList(SConceptOperations.getDirectSuperConcepts(concept, false))) {
      res = convert(superconcept, sourceNode);
      if (res != null) {
        return res;
      }
    }

    return null;
  }

  protected R convert(SAbstractConcept concept, S sourceNode, List<TypeConverter<S, R>> list) {
    if (list == null) {
      return null;
    }
    for (TypeConverter<S, R> converter : ListSequence.fromList(list)) {
      R result = converter.convert(sourceNode, this);
      if (result != null) {
        return result;
      }
    }
    return null;
  }
}
