package jetbrains.mps.ide.devkit.actions;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import jetbrains.mps.project.MPSProject;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.ide.findusages.model.scopes.ProjectScope;
import jetbrains.mps.ide.findusages.model.IResultProvider;
import jetbrains.mps.ide.findusages.view.FindUtils;
import jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.BaseNode;
import jetbrains.mps.ide.findusages.model.SearchQuery;
import jetbrains.mps.ide.findusages.findalgorithm.finders.IFinder;
import org.jetbrains.mps.openapi.util.ProgressMonitor;
import jetbrains.mps.ide.findusages.model.SearchResult;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.ide.findusages.findalgorithm.finders.SearchedObjects;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.ide.findusages.view.UsageToolOptions;
import jetbrains.mps.ide.findusages.model.SearchObjectResolver;
import jetbrains.mps.ide.findusages.model.holders.GenericHolder;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.ide.findusages.view.UsagesViewTool;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class FindRootableConceptsWithoutIcons_Action extends BaseAction {
  private static final Icon ICON = null;

  public FindRootableConceptsWithoutIcons_Action() {
    super("Find Rootable Concepts without Icons", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(ActionAccess.NONE);
    updateInBackground(true);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      MPSProject p = event.getData(MPSCommonDataKeys.MPS_PROJECT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    final MPSProject mpsProject = event.getData(MPSCommonDataKeys.MPS_PROJECT);
    ProjectScope scope = mpsProject.getModelAccess().computeReadAction(() -> new ProjectScope(mpsProject));
    final IResultProvider rp0 = FindUtils.makeProvider("jetbrains.mps.lang.structure.findUsages.ConceptInstances_Finder");
    // FIXME desperately need filtering IResultProvider
    IResultProvider rpFilter = new BaseNode() {
      @Override
      protected void doFindResults(@NotNull SearchQuery query, @NotNull final IFinder.FindCallback callback, @NotNull ProgressMonitor monitor) {
        rp0.findResults(query, new IFinder.FindCallback() {
          @Override
          public void onUsageFound(@NotNull SearchResult<?> result) {
            SNode node = (SNode) result.getObject();
            if (SPropertyOperations.getBoolean(node, PROPS.rootable$_9pz) && (SLinkOperations.getTarget(node, LINKS.icon$HKhR) == null)) {
              callback.onUsageFound(result);
            }
          }

          @Override
          public void onSearchedObjectsCalculated(@NotNull SearchedObjects<?> searchedObjects) {
            callback.onSearchedObjectsCalculated(searchedObjects);
          }
        }, monitor);
      }

      @Override
      public long getEstimatedTime(SearchScope scope) {
        return rp0.getEstimatedTime(scope);
      }
    };
    UsageToolOptions opt = new UsageToolOptions().allowRunAgain(true).navigateIfSingle(true).forceNewTab(true).notFoundMessage("no concepts without icons");
    SearchObjectResolver.BasicResolver soResolver = new SearchObjectResolver.BasicResolver(mpsProject.getRepository());
    SearchQuery sq = new SearchQuery(new GenericHolder<>(new SNodePointer("r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)", "1071489090640"), "ConceptDeclaration"), soResolver, scope);
    UsagesViewTool.showUsages(mpsProject.getProject(), rpFilter, sq, opt);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink icon$HKhR = MetaAdapterFactory.getContainmentLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979ba0450L, 0x57cf4eb14c4f9ef5L, "icon");
  }

  private static final class PROPS {
    /*package*/ static final SProperty rootable$_9pz = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979ba0450L, 0xff49c1d648L, "rootable");
  }
}
