package jetbrains.mps.lang.test.junit5;

/*Generated by MPS */

import jetbrains.mps.tool.environment.Environment;
import jetbrains.mps.lang.test.launcher.WorkerCallback;
import jetbrains.mps.tool.common.Script;
import jetbrains.mps.project.Project;
import jetbrains.mps.baseLanguage.unitTest.runtime.EnvironmentAwareExtension;
import org.junit.platform.commons.PreconditionViolationException;
import org.junit.platform.launcher.core.LauncherConfig;
import org.junit.vintage.engine.VintageTestEngine;
import org.junit.jupiter.engine.JupiterTestEngine;
import org.junit.platform.launcher.Launcher;
import org.junit.platform.launcher.core.LauncherFactory;
import jetbrains.mps.lang.test.junit5.tcutil.JUnit5TestExecutionListener;
import java.io.File;
import org.junit.platform.reporting.legacy.xml.LegacyXmlReportGeneratingListener;
import java.io.PrintWriter;
import org.junit.platform.launcher.LauncherDiscoveryRequest;
import java.util.List;
import org.junit.platform.engine.DiscoverySelector;
import org.junit.platform.engine.discovery.DiscoverySelectors;
import java.util.stream.Collectors;
import org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SNode;

public class JUnit5Launcher {

  public static final String HALT_ON_FAILURE = "launchtests.haltonfailure";
  public static final String TEST_REPORTS_DIR = "launchtests.testReportsDir";

  private final Environment myEnvironment;
  private final WorkerCallback myWorkerCallback;
  private final Script myWhatToDo;

  public JUnit5Launcher(Script whatToDo, Environment environment, WorkerCallback callback) {
    this.myWhatToDo = whatToDo;
    this.myEnvironment = environment;
    this.myWorkerCallback = callback;
  }

  public void launchTests() {
    Project project = myEnvironment.createProject(new ModuleFilesListProjectStrategy(myWhatToDo.getModules()));
    EnvironmentAwareExtension.setEnvironment(myEnvironment);

    FailureDetector failureDetector = new FailureDetector();

    launchTests(project, failureDetector);

    myEnvironment.closeProject(project);
    myEnvironment.dispose();

    if (isHaltOnFailure() && failureDetector.hasFailures()) {
      failureDetector.flushErrors(myWorkerCallback);
      myWorkerCallback.failBuild();
    }
  }

  private void launchTests(Project project, FailureDetector failureDetector) throws PreconditionViolationException {
    LauncherConfig launcherConfig = LauncherConfig.builder().enableTestEngineAutoRegistration(false).enablePostDiscoveryFilterAutoRegistration(false).enableLauncherSessionListenerAutoRegistration(false).enableLauncherDiscoveryListenerAutoRegistration(false).enableTestExecutionListenerAutoRegistration(false).addTestEngines(new VintageTestEngine(), new JupiterTestEngine()).build();
    Launcher launcher = LauncherFactory.openSession(launcherConfig).getLauncher();
    if (isRunningOnTeamCity()) {
      launcher.registerTestExecutionListeners(new JUnit5TestExecutionListener());
    }
    File testReportsDir = getTestReportsDir();
    if (testReportsDir != null) {
      launcher.registerTestExecutionListeners(new LegacyXmlReportGeneratingListener(testReportsDir.toPath(), new PrintWriter(System.out)));
    }
    launcher.registerTestExecutionListeners(failureDetector);
    launcher.execute(buildRequest(collectTestClasses(project)));
  }

  private LauncherDiscoveryRequest buildRequest(final List<Class<?>> testClasses) {
    List<DiscoverySelector> testSelectors = testClasses.stream().map((Class<?> testClass) -> DiscoverySelectors.selectClass(testClass)).collect(Collectors.<DiscoverySelector>toList());

    return LauncherDiscoveryRequestBuilder.request().selectors(testSelectors).configurationParameter("junit.platform.output.capture.stdout", "true").configurationParameter("junit.platform.output.capture.stderr", "true").build();
  }

  private List<Class<?>> collectTestClasses(final Project project) {
    final List<Class<?>> testClasses = new ArrayList<>();
    final TestDiscoveryVisitor visitor = new TestDiscoveryVisitor() {
      @Override
      public void visitTestRoot(SNode testRootNode, String testClassName, ClassLoader moduleClassLoader) {
        try {
          testClasses.add(moduleClassLoader.loadClass(testClassName));

        } catch (ClassNotFoundException e) {
          myWorkerCallback.error("error building test suite", e);
        }
      }
    };

    project.getModelAccess().runReadAction(() -> {

      new TestDiscovery(visitor).surveyModules(project.getProjectModules());

    });

    return testClasses;
  }

  private boolean isHaltOnFailure() {
    String property = myWhatToDo.getProperty(HALT_ON_FAILURE);
    return (property != null ? Boolean.valueOf(property) : false);
  }

  private File getTestReportsDir() {
    String property = myWhatToDo.getProperty(TEST_REPORTS_DIR);
    if (property == null) {
      return null;
    }
    File dir = new File(property);
    if (!(dir.exists())) {
      if (!(dir.mkdirs())) {
        myWorkerCallback.error("could not create directory for test reports: " + dir.getAbsolutePath());
        return null;
      }
    }
    if (!(dir.isDirectory())) {
      myWorkerCallback.error("not a directory: " + dir.getAbsolutePath());
      return null;
    }
    return dir;
  }

  private boolean isRunningOnTeamCity() {
    return myWhatToDo.getProperty("teamcity.version") != null;
  }

}
