package jetbrains.mps.kotlin.baseLanguage.toJava;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.kotlin.baseLanguage.typeConversion.TypeConverterEngine;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class JavaGenericClassTypeBuilder extends JavaClassTypeBuilder {
  public JavaGenericClassTypeBuilder(SNodeReference targetClass) {
    super(targetClass);
  }


  @Override
  public SNode convert(SNode source, final TypeConverterEngine<SNode, SNode> engine) {
    SNode converted = super.convert(source, engine);
    ListSequence.fromList(SLinkOperations.getChildren(converted, LINKS.parameter$oqG$)).addSequence(ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(source, CONCEPTS.ClassType$jI), LINKS.typeProjections$vhti)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return KtToJavaEngine.convertProjection(it, engine);
      }
    }));
    return converted;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink parameter$oqG$ = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x102419671abL, "parameter");
    /*package*/ static final SContainmentLink typeProjections$vhti = MetaAdapterFactory.getContainmentLink(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x5b1dd60162c97579L, 0x5b1dd60162c9757cL, "typeProjections");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ClassType$jI = MetaAdapterFactory.getConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af4dfL, "jetbrains.mps.kotlin.structure.ClassType");
  }
}
