package jetbrains.mps.debugger.api.ui.icons;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import javax.swing.Icon;
import com.intellij.icons.AllIcons;
import jetbrains.mps.icons.MPSIcons;

@GeneratedClass(nodeId = "4474271214083117745", model = "r:e60874cf-5ffd-4123-9760-5f88ff8e0a5a(jetbrains.mps.debugger.api.ui.icons)")
public class Icons {
  public static final Icon BREAKPOINT = AllIcons.Debugger.Db_set_breakpoint;
  public static final Icon INV_BREAKPOINT = AllIcons.Debugger.Db_invalid_breakpoint;
  public static final Icon DISABLED_BREAKPOINT = AllIcons.Debugger.Db_disabled_breakpoint;
  public static final Icon MUTED_BREAKPOINT = AllIcons.Debugger.Db_muted_breakpoint;
  public static final Icon SHOW_AS_TREE = AllIcons.Actions.ShowAsTree;
  public static final Icon FRAMES = AllIcons.Debugger.Frame;
  public static final Icon VARIABLES = AllIcons.Debugger.Value;
  public static final Icon WATCHES = AllIcons.Debugger.Watch;
  public static final Icon BREAKPOINTS_DIALOG_DELETE = MPSIcons.Debug.DeleteBreakpoint;
  public static final Icon BREAKPOINTS_DIALOG_ADD = MPSIcons.Debug.AddBreakPoint;
  public static final Icon BREAKPOINTS_DIALOG_GOTO = MPSIcons.Debug.GoToSource;
  public static final Icon BREAKPOINTS_DIALOG_GROUP_BY_MODEL = MPSIcons.Actions.GroupByModel;
  public static final Icon BREAKPOINTS_DIALOG_GROUP_BY_MODULE = MPSIcons.Actions.GroupByModule;
  public static final Icon BREAKPOINTS_DIALOG_GROUP_BY_ROOT = MPSIcons.Actions.GroupByRoot;
  public static final Icon BREAKPOINTS_DIALOG_VIEW_SOURCE = AllIcons.Actions.ShowCode;
  public static final Icon BREAKPOINTS_DIALOG_TREE_VIEW = AllIcons.Actions.ShowAsTree;
  public Icons() {
  }
}
