package jetbrains.mps.baseLanguage.unitTest.execution;

/*Generated by MPS */

import org.jetbrains.mps.annotations.Immutable;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collections;
import org.jetbrains.mps.annotations.ImmutableReturn;

@Immutable
public final class TerminationTestEvent {
  private final List<TestMethodNodeKey> myNotRanTests;
  private final TestNodeKey myCurrentRunningTest;
  private final boolean myTerminatedCorrectly;

  public TerminationTestEvent(@Nullable TestNodeKey myRunningTestDuringTermination, @NotNull List<TestMethodNodeKey> notRanTests, boolean terminatedcorrectly) {
    myCurrentRunningTest = myRunningTestDuringTermination;
    myNotRanTests = Collections.unmodifiableList(notRanTests);
    myTerminatedCorrectly = terminatedcorrectly;
  }

  @Nullable
  public TestNodeKey getCurrentRunningTest() {
    return myCurrentRunningTest;
  }

  @ImmutableReturn
  public List<TestMethodNodeKey> getNotRanTests() {
    return myNotRanTests;
  }

  public boolean isTerminatedCorrectly() {
    return myTerminatedCorrectly;
  }
}
