package jetbrains.mps.baseLanguage.unitTest.execution;

/*Generated by MPS */

import org.jetbrains.mps.annotations.Immutable;
import org.jetbrains.annotations.NotNull;

/**
 * messages from the process come as strings so the keys here are strings
 */
@Immutable
public final class TestCaseStringKey implements TestRawKey {
  private final String myTestCaseFqName;

  public TestCaseStringKey(@NotNull String testCaseFqName) {
    myTestCaseFqName = testCaseFqName;
  }

  @Override
  public String getTestCaseFqName() {
    return myTestCaseFqName;
  }

  @Override
  public String getQualifiedName() {
    return myTestCaseFqName;
  }

  @Override
  public boolean equals(Object object) {
    if (object instanceof TestCaseStringKey) {
      return myTestCaseFqName.equals(((TestCaseStringKey) object).myTestCaseFqName);
    }
    return false;
  }

  @Override
  public int hashCode() {
    return myTestCaseFqName.hashCode();
  }

  @Override
  public String toString() {
    return "TestCaseKey[" + myTestCaseFqName + "]";
  }


  @NotNull
  @Override
  public TestType getType() {
    return TestType.TESTCASE;
  }
}
