package jetbrains.mps.baseLanguage.overloadedOperators.util;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.internal.collections.runtime.IMapping;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class BinaryOperationUtil {
  private SModel myModel;
  public BinaryOperationUtil(SModel m) {
    myModel = m;
  }
  private Iterable<SNode> getOperatorContainers() {
    Iterable<SNode> visibleContainers = SLinkOperations.collect(SModelOperations.roots(myModel, CONCEPTS.ContainerImport$sY), LINKS.container$EWeH);
    if (Sequence.fromIterable(visibleContainers).isEmpty()) {
      visibleContainers = SModelOperations.rootsIncludingImported(myModel, CONCEPTS.OverloadedOperatorContainer$6f);
    }
    return SLinkOperations.collectMany(visibleContainers, LINKS.operators$c9kJ);
  }
  public boolean hasOverloadedOperators(SNode node, SNode leftType, SNode rightType) {
    for (SNode operator : getOperatorContainers()) {
      if (isOverloading(node, leftType, rightType, operator)) {
        return true;
      }
      if (SPropertyOperations.getBoolean(operator, PROPS.commutative$t4aS) && isOverloading(SNodeOperations.cast(node, CONCEPTS.BinaryOperation$W1), rightType, leftType, operator)) {
        return true;
      }
    }
    return false;
  }
  private Map<SNode, Boolean> getOverloadedOperators(SNode node, SNode leftType, SNode rightType) {
    Map<SNode, Boolean> result = MapSequence.fromMap(new HashMap<SNode, Boolean>());
    if (!(SNodeOperations.isInstanceOf(node, CONCEPTS.BinaryOperation$W1))) {
      return result;
    }
    for (SNode operator : getOperatorContainers()) {
      if (isOverloading(SNodeOperations.cast(node, CONCEPTS.BinaryOperation$W1), leftType, rightType, operator)) {
        MapSequence.fromMap(result).put(operator, false);
      }
      if (SPropertyOperations.getBoolean(operator, PROPS.commutative$t4aS) && isOverloading(SNodeOperations.cast(node, CONCEPTS.BinaryOperation$W1), rightType, leftType, operator)) {
        MapSequence.fromMap(result).put(operator, true);
      }
    }
    return result;
  }
  private static boolean isOverloading(SNode node, SNode leftType, SNode rightType, SNode operator) {
    if (!((TypecheckingFacade.getFromContext().isSubtype(leftType, SLinkOperations.getTarget(operator, LINKS.leftType$aTVX)) && TypecheckingFacade.getFromContext().isSubtype(rightType, SLinkOperations.getTarget(operator, LINKS.rightType$aUaY))))) {
      return false;
    }
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(operator, LINKS.operator$XXCg), CONCEPTS.BinaryOperationReference$wm)) {
      if (SNodeOperations.isInstanceOf(node, SNodeOperations.asSConcept(SNodeOperations.asSConcept(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(operator, LINKS.operator$XXCg), CONCEPTS.BinaryOperationReference$wm), LINKS.binaryOperation$5SHJ))))) {
        return true;
      }
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(operator, LINKS.operator$XXCg), CONCEPTS.CustomOperator$OA) && SNodeOperations.isInstanceOf(node, CONCEPTS.CustomOperatorUsage$Hd)) {
      if (SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.CustomOperatorUsage$Hd), LINKS.operator$R44$) == SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(operator, LINKS.operator$XXCg), CONCEPTS.CustomOperator$OA), LINKS.declaration$Tz4K)) {
        return true;
      }
    }
    return false;
  }
  private static boolean isSubTypeOperatorStraight(SNode subOperator, SNode superOperator) {
    if (TypecheckingFacade.getFromContext().isStrongSubtype(SLinkOperations.getTarget(superOperator, LINKS.leftType$aTVX), SLinkOperations.getTarget(subOperator, LINKS.leftType$aTVX))) {
      return false;
    }
    if (TypecheckingFacade.getFromContext().isStrongSubtype(SLinkOperations.getTarget(subOperator, LINKS.leftType$aTVX), SLinkOperations.getTarget(superOperator, LINKS.leftType$aTVX))) {
      return true;
    }
    if (TypecheckingFacade.getFromContext().isStrongSubtype(SLinkOperations.getTarget(superOperator, LINKS.rightType$aUaY), SLinkOperations.getTarget(subOperator, LINKS.rightType$aUaY))) {
      return false;
    }
    return true;
  }
  private static boolean isReversedSubTypeOperator(SNode subOperator, SNode superOperator) {
    if (TypecheckingFacade.getFromContext().isStrongSubtype(SLinkOperations.getTarget(superOperator, LINKS.rightType$aUaY), SLinkOperations.getTarget(subOperator, LINKS.leftType$aTVX))) {
      return false;
    }
    if (TypecheckingFacade.getFromContext().isStrongSubtype(SLinkOperations.getTarget(subOperator, LINKS.leftType$aTVX), SLinkOperations.getTarget(superOperator, LINKS.rightType$aUaY))) {
      return true;
    }
    if (TypecheckingFacade.getFromContext().isStrongSubtype(SLinkOperations.getTarget(superOperator, LINKS.leftType$aTVX), SLinkOperations.getTarget(subOperator, LINKS.rightType$aUaY))) {
      return false;
    }
    return true;
  }
  private static boolean isSubTypeOperator(SNode subOperator, SNode superOperator, boolean reversed) {
    if (!(reversed)) {
      return isSubTypeOperatorStraight(subOperator, superOperator);
    }
    return isReversedSubTypeOperator(subOperator, superOperator);
  }
  public SNode getNearestOverloaded(SNode node, SNode leftType, SNode rightType) {
    if (!(SNodeOperations.isInstanceOf(node, CONCEPTS.BinaryOperation$W1))) {
      return null;
    }
    SNode result = (SNode) (node.getUserObject("operator"));
    if (result != null) {
      return result;
    }
    Map<SNode, Boolean> operatorMap = getOverloadedOperators(SNodeOperations.cast(node, CONCEPTS.BinaryOperation$W1), leftType, rightType);
    if (MapSequence.fromMap(operatorMap).isEmpty()) {
      return null;
    }
    result = MapSequence.fromMap(operatorMap).first().key();
    boolean resultReversed = MapSequence.fromMap(operatorMap).first().value();
    for (IMapping<SNode, Boolean> operatorEntry : MapSequence.fromMap(operatorMap)) {
      SNode operator = operatorEntry.key();
      boolean reversed = operatorEntry.value() != resultReversed;
      if (isSubTypeOperator(operator, result, reversed)) {
        result = operator;
        resultReversed = operatorEntry.value();
      }
    }
    node.putUserObject("operator", result);
    node.putUserObject("reversed", resultReversed);
    return result;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ContainerImport$sY = MetaAdapterFactory.getConcept(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x66302c3c8df72c49L, "jetbrains.mps.baseLanguage.overloadedOperators.structure.ContainerImport");
    /*package*/ static final SConcept OverloadedOperatorContainer$6f = MetaAdapterFactory.getConcept(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x6b6f5c413011207L, "jetbrains.mps.baseLanguage.overloadedOperators.structure.OverloadedOperatorContainer");
    /*package*/ static final SConcept BinaryOperation$W1 = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, "jetbrains.mps.baseLanguage.structure.BinaryOperation");
    /*package*/ static final SConcept BinaryOperationReference$wm = MetaAdapterFactory.getConcept(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x2764eda929d23eb4L, "jetbrains.mps.baseLanguage.overloadedOperators.structure.BinaryOperationReference");
    /*package*/ static final SConcept CustomOperatorUsage$Hd = MetaAdapterFactory.getConcept(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x15c86fdc6084766fL, "jetbrains.mps.baseLanguage.overloadedOperators.structure.CustomOperatorUsage");
    /*package*/ static final SConcept CustomOperator$OA = MetaAdapterFactory.getConcept(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x2764eda929d60237L, "jetbrains.mps.baseLanguage.overloadedOperators.structure.CustomOperator");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink container$EWeH = MetaAdapterFactory.getReferenceLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x66302c3c8df72c49L, 0x66302c3c8df72d45L, "container");
    /*package*/ static final SContainmentLink operators$c9kJ = MetaAdapterFactory.getContainmentLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x6b6f5c413011207L, 0x6b6f5c413011208L, "operators");
    /*package*/ static final SContainmentLink leftType$aTVX = MetaAdapterFactory.getContainmentLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x6b6f5c41300f84dL, 0x5cab13b82bf359b1L, "leftType");
    /*package*/ static final SContainmentLink rightType$aUaY = MetaAdapterFactory.getContainmentLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x6b6f5c41300f84dL, 0x5cab13b82bf359b2L, "rightType");
    /*package*/ static final SContainmentLink operator$XXCg = MetaAdapterFactory.getContainmentLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x6b6f5c41300f84dL, 0x2764eda929d23eb6L, "operator");
    /*package*/ static final SReferenceLink binaryOperation$5SHJ = MetaAdapterFactory.getReferenceLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x2764eda929d23eb4L, 0x2764eda929d23eb5L, "binaryOperation");
    /*package*/ static final SReferenceLink declaration$Tz4K = MetaAdapterFactory.getReferenceLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x2764eda929d60237L, 0x2764eda929d60239L, "declaration");
    /*package*/ static final SReferenceLink operator$R44$ = MetaAdapterFactory.getReferenceLink(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x15c86fdc6084766fL, 0x15c86fdc60847670L, "operator");
  }

  private static final class PROPS {
    /*package*/ static final SProperty commutative$t4aS = MetaAdapterFactory.getProperty(0xfc8d557e5de64dd8L, 0xb749aab2fb23aefcL, 0x6b6f5c41300f84dL, 0x2519632ce12e26e2L, "commutative");
  }
}
