package jetbrains.mps.lang.constraints.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class ConstraintFunctionParameter_containingLink_SubstituteMenu extends SubstituteMenuBase {
  public ConstraintFunctionParameter_containingLink_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "ConstraintFunctionParameter_containingLink", new SNodePointer("r:00000000-0000-4000-0000-011c89590308(jetbrains.mps.lang.constraints.editor)", "1741258697587239325")));
  }

}
