package jetbrains.mps.lang.editor.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class ConceptFunctionParameter_selectedNode_SubstituteMenu extends SubstituteMenuBase {
  public ConceptFunctionParameter_selectedNode_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "ConceptFunctionParameter_selectedNode", new SNodePointer("r:00000000-0000-4000-0000-011c89590299(jetbrains.mps.lang.editor.editor)", "1741258697587154173")));
  }

}
