package jetbrains.mps.lang.smodel.query.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class QueryParameterScope_old_SubstituteMenu extends SubstituteMenuBase {
  public QueryParameterScope_old_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "QueryParameterScope_old", new SNodePointer("r:be520d7c-8791-490a-9d50-1adca7cd12c4(jetbrains.mps.lang.smodel.query.editor)", "8064924659634133080")));
  }

}
