package jetbrains.mps.lang.constraints.rules.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AbstractConstraintsDefNative;
  private ConceptPresentation props_ApplicableCondition;
  private ConceptPresentation props_ApplicableConditionHolder;
  private ConceptPresentation props_Block;
  private ConceptPresentation props_ConstraintsDef;
  private ConceptPresentation props_ConstraintsDefNative;
  private ConceptPresentation props_ConstraintsDefNativeNode;
  private ConceptPresentation props_ConstraintsExpressionHolder;
  private ConceptPresentation props_ConstraintsRoot2;
  private ConceptPresentation props_ConstraintsRule;
  private ConceptPresentation props_ConstraintsRuleIdHolder;
  private ConceptPresentation props_ContextReference;
  private ConceptPresentation props_PseudoBaseConcept;
  private ConceptPresentation props_RuleBlock;
  private ConceptPresentation props_RuleBlockMember;
  private ConceptPresentation props_RuleKind;
  private ConceptPresentation props_RuleKindParameterConcept;
  private ConceptPresentation props_TypedIdentifier;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AbstractConstraintsDefNative:
        if (props_AbstractConstraintsDefNative == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AbstractConstraintsDefNative = cpb.create();
        }
        return props_AbstractConstraintsDefNative;
      case LanguageConceptSwitch.ApplicableCondition:
        if (props_ApplicableCondition == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("when");
          props_ApplicableCondition = cpb.create();
        }
        return props_ApplicableCondition;
      case LanguageConceptSwitch.ApplicableConditionHolder:
        if (props_ApplicableConditionHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ApplicableConditionHolder = cpb.create();
        }
        return props_ApplicableConditionHolder;
      case LanguageConceptSwitch.Block:
        if (props_Block == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Block = cpb.create();
        }
        return props_Block;
      case LanguageConceptSwitch.ConstraintsDef:
        if (props_ConstraintsDef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConstraintsDef = cpb.create();
        }
        return props_ConstraintsDef;
      case LanguageConceptSwitch.ConstraintsDefNative:
        if (props_ConstraintsDefNative == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConstraintsDefNative = cpb.create();
        }
        return props_ConstraintsDefNative;
      case LanguageConceptSwitch.ConstraintsDefNativeNode:
        if (props_ConstraintsDefNativeNode == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConstraintsDefNativeNode = cpb.create();
        }
        return props_ConstraintsDefNativeNode;
      case LanguageConceptSwitch.ConstraintsExpressionHolder:
        if (props_ConstraintsExpressionHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ConstraintsExpressionHolder = cpb.create();
        }
        return props_ConstraintsExpressionHolder;
      case LanguageConceptSwitch.ConstraintsRoot2:
        if (props_ConstraintsRoot2 == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConstraintsRoot2 = cpb.create();
        }
        return props_ConstraintsRoot2;
      case LanguageConceptSwitch.ConstraintsRule:
        if (props_ConstraintsRule == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("constraints rule");
          cpb.presentationByName();
          props_ConstraintsRule = cpb.create();
        }
        return props_ConstraintsRule;
      case LanguageConceptSwitch.ConstraintsRuleIdHolder:
        if (props_ConstraintsRuleIdHolder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ConstraintsRuleIdHolder = cpb.create();
        }
        return props_ConstraintsRuleIdHolder;
      case LanguageConceptSwitch.ContextReference:
        if (props_ContextReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x47257bf378d3470bL, 0x89d98c3261a61d15L, 0x6530303593574311L, 0x6530303593578e5eL, "declaration", "", "");
          props_ContextReference = cpb.create();
        }
        return props_ContextReference;
      case LanguageConceptSwitch.PseudoBaseConcept:
        if (props_PseudoBaseConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_PseudoBaseConcept = cpb.create();
        }
        return props_PseudoBaseConcept;
      case LanguageConceptSwitch.RuleBlock:
        if (props_RuleBlock == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Add rules for the kind");
          props_RuleBlock = cpb.create();
        }
        return props_RuleBlock;
      case LanguageConceptSwitch.RuleBlockMember:
        if (props_RuleBlockMember == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_RuleBlockMember = cpb.create();
        }
        return props_RuleBlockMember;
      case LanguageConceptSwitch.RuleKind:
        if (props_RuleKind == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RuleKind = cpb.create();
        }
        return props_RuleKind;
      case LanguageConceptSwitch.RuleKindParameterConcept:
        if (props_RuleKindParameterConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RuleKindParameterConcept = cpb.create();
        }
        return props_RuleKindParameterConcept;
      case LanguageConceptSwitch.TypedIdentifier:
        if (props_TypedIdentifier == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_TypedIdentifier = cpb.create();
        }
        return props_TypedIdentifier;
    }
    return null;
  }
}
