package Samples;

/*Generated by MPS */


public final class DropBox<T> {
  private T storage;
  public DropBox() {
    // UseAlt+Enterontheclassnametomarkitasthread-safeornon-thread-safe
    // Theseetheeffectithasontheerror/warningreportingintheThreadSafeSampleclass
  }
  public synchronized void store(T value) throws InterruptedException {
    while (storage != null) {
      this.wait();
    }
    storage = value;
    this.notify();
  }
  public synchronized T retrieve() throws InterruptedException {
    while (storage == null) {
      this.wait();
    }
    T pom = storage;
    storage = null;
    this.notify();
    return pom;
  }
}
