package jetbrains.mps.samples.ChemMastery.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Compound_Constraints extends BaseConstraintsDescriptor {
  public Compound_Constraints() {
    super(CONCEPTS.Compound$6W);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Compound$6W = MetaAdapterFactory.getConcept(0xa9a262e8f8054598L, 0x88c614f38937d309L, 0x6ef7184faba62978L, "jetbrains.mps.samples.ChemMastery.structure.Compound");
  }
}
