package jetbrains.mps.baseLanguage.unitTest.sandbox;

/*Generated by MPS */

import org.junit.Test;
import org.junit.Assert;

public abstract class AbstractTest4Class {
  public AbstractTest4Class() {
  }
  @Test
  public void testMethod4() {
    Assert.assertEquals("true", "false");
  }
}
