package jetbrains.mps.lang.test.matcher;

/*Generated by MPS */


public final class UnmatchedNode extends DifferenceItem {
  public UnmatchedNode() {
  }

  @Override
  public String toString() {
    return "Excessive node, no counterpart to match to";
  }
}
