package jetbrains.mps.vcs.annotate;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.vcs.history.VcsFileRevision;

@GeneratedClass(node = "r:f509a650-cbd9-47e7-b2a0-79f49c562c0b(jetbrains.mps.vcs.annotate)/6338414166361132708", model = "r:f509a650-cbd9-47e7-b2a0-79f49c562c0b(jetbrains.mps.vcs.annotate)")
public final class LineAnnotation {

  @NotNull
  private final VcsFileRevision myRevision;
  private final VcsFileRevision myPrevRevision;
  private final String myDescription;


  public LineAnnotation(@NotNull VcsFileRevision revision, VcsFileRevision prevRevision, String description) {
    myRevision = revision;
    myPrevRevision = prevRevision;
    myDescription = description;
  }

  public String getDescription() {
    return myDescription;
  }

  @NotNull
  public VcsFileRevision getRevision() {
    return myRevision;
  }

  public VcsFileRevision getPrevRevision() {
    return myPrevRevision;
  }

  public boolean isEarlierThanRevision(@NotNull VcsFileRevision revision) {
    return revision != myRevision && revision.getRevisionDate().compareTo(myRevision.getRevisionDate()) > 0;
  }
}
