package jetbrains.mps.vcs.annotate;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import jetbrains.mps.workbench.action.BaseGroup;
import jetbrains.mps.workbench.action.BaseAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import com.intellij.openapi.vcs.history.VcsFileRevision;
import com.intellij.openapi.vcs.history.VcsRevisionNumber;
import com.intellij.openapi.vcs.history.ShortVcsRevisionNumber;

@GeneratedClass(node = "r:f509a650-cbd9-47e7-b2a0-79f49c562c0b(jetbrains.mps.vcs.annotate)/7744421503924576834", model = "r:f509a650-cbd9-47e7-b2a0-79f49c562c0b(jetbrains.mps.vcs.annotate)")
public class VcsRevisionRange extends BaseGroup {
  private AnnotationColumn myColumn;
  public VcsRevisionRange(AnnotationColumn column) {
    super("Revision Range");
    myColumn = column;
    setPopup(false);
    add(new BaseAction("Remove Highlighting") {
      @Override
      protected void doExecute(AnActionEvent event, Map<String, Object> map) {
        myColumn.invalidateLayout();
      }
    });
  }


  private static String revisionToString(VcsFileRevision revision) {
    VcsRevisionNumber number = revision.getRevisionNumber();
    if (number instanceof ShortVcsRevisionNumber) {
      return ((ShortVcsRevisionNumber) number).toShortString();
    } else {
      return number.asString();
    }
  }

}
