package jetbrains.mps.lang.refactoring.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;
import com.intellij.ui.ExperimentalUI;

public class IconContainer {
  protected static IconResource RESOURCE_a0a4a0a0a1 = (ExperimentalUI.isNewUI() ? new IconResource("refactoringsModel_newui.svg", IconContainer.class) : new IconResource("refactoringsModel.png", IconContainer.class));
}
