package multiAspectLang2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptA = createDescriptorForA();
  /*package*/ final ConceptDescriptor myConceptTestConcept = createDescriptorForTestConcept();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptA, myConceptTestConcept);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.A:
        return myConceptA;
      case LanguageConceptSwitch.TestConcept:
        return myConceptTestConcept;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForA() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("multiAspectLang2", "A", 0xb1c5ce448c754a1bL, 0xa0894c3f4cb39077L, 0x20849d33c9744322L);
    b.class_(false, false, false);
    b.origin("r:983174f3-f45a-49c3-a41a-fa014f164dbe(multiAspectLang2.structure)/2343170551888233250");
    b.version(2);
    b.property("prop", 0x36944cbfd5d06b46L).type(PrimitiveTypeId.INTEGER).origin("3932852761410956102").done();
    b.associate("ref", 0x20849d33c974ff1cL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL).optional(true).origin("2343170551888281372").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("multiAspectLang2", "TestConcept", 0xb1c5ce448c754a1bL, 0xa0894c3f4cb39077L, 0x530a123e5fc34d34L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:983174f3-f45a-49c3-a41a-fa014f164dbe(multiAspectLang2.structure)/5983615114019032372");
    b.version(2);
    b.property("prop", 0x50310db2af989958L).type(PrimitiveTypeId.INTEGER).origin("5778414857994410328").done();
    b.associate("link", 0x161a25d497067a9eL).target(0xb1c5ce448c754a1bL, 0xa0894c3f4cb39077L, 0x530a123e5fc34d34L).optional(true).origin("1592627013225970334").done();
    return b.create();
  }
}
