package jetbrains.mps.tool.common;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import java.util.List;
import java.util.ArrayList;
import org.jdom.Element;

/**
 * Outlines tests to be executed.
 * Could be "TestPlan" but as long as we use ...Data suffix,
 */
@GeneratedClass(nodeId = "6304375679895287390", model = "r:067fd2c9-d009-4506-91db-a69992d65964(jetbrains.mps.tool.common)")
public final class TestData {
  private static final String E_MODULE = "module";
  private static final String E_CONTAINER = "testcase";
  private static final String E_TEST = "test";
  private static final String A_QNAME = "fqn";
  private static final String A_PTR = "ptr";
  private static final String A_DISCOVER = "discover";

  public final List<ModuleRecord> testModules = new ArrayList<>();

  public void read(Element parent) {
    for (Element tme : parent.getChildren(E_MODULE)) {
      if (tme.getAttributeBooleanValue(A_DISCOVER)) {
        testModules.add(new ModuleRecord(tme.getAttributeValue(A_PTR), true));
      } else {
        ModuleRecord mr = new ModuleRecord(tme.getAttributeValue(A_PTR), false);
        testModules.add(mr);
        for (Element tce : tme.getChildren(E_CONTAINER)) {
          TestContainerRecord tcr = new TestContainerRecord(tce.getAttributeValue(A_QNAME));
          mr.testCases.add(tcr);
          for (Element tre : tce.getChildren(E_TEST)) {
            tcr.tests.add(new TestRecord(tre.getAttributeValue(A_QNAME)));
          }
        }
      }
    }
  }

  public void write(Element parent) {
    for (ModuleRecord mr : testModules) {
      Element tme = new Element(E_MODULE);
      tme.setAttribute(A_PTR, mr.modulePtr);
      if (mr.autoDiscovery) {
        tme.setAttribute(A_DISCOVER, Boolean.toString(true));
        continue;
      }
      for (TestContainerRecord tcr : mr.testCases) {
        Element tce = new Element(E_CONTAINER);
        tce.setAttribute(A_QNAME, tcr.qualifiedName);
        for (TestRecord tr : tcr.tests) {
          Element tre = new Element(E_TEST);
          tre.setAttribute(A_QNAME, tr.qualifiedName);
          tce.addContent(tre);
        }
        tme.addContent(tce);
      }
      parent.addContent(tme);
    }
  }

  public static final class ModuleRecord {
    public final String modulePtr;
    public final boolean autoDiscovery;
    public final List<TestContainerRecord> testCases = new ArrayList<>();

    public ModuleRecord(String modulePtr) {
      this(modulePtr, false);
    }

    public ModuleRecord(String modulePtr, boolean autoDiscovery) {
      this.modulePtr = modulePtr;
      this.autoDiscovery = autoDiscovery;
    }
  }

  public static class TestContainerRecord {
    public final String qualifiedName;
    public final List<TestRecord> tests = new ArrayList<>();

    public TestContainerRecord(String qualifiedName) {
      this.qualifiedName = qualifiedName;
    }
  }

  public static class TestRecord {
    public final String qualifiedName;

    public TestRecord(String qualifiedName) {
      this.qualifiedName = qualifiedName;
    }
  }
}
