package jetbrains.mps.vcs.diff.changes;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNodeId;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import java.util.Set;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

@GeneratedClass(node = "r:9b4a89e1-ec38-42c4-b1bd-96ab47ffcb3f(jetbrains.mps.vcs.diff.changes)/4676109734476338389", model = "r:9b4a89e1-ec38-42c4-b1bd-96ab47ffcb3f(jetbrains.mps.vcs.diff.changes)")
public final class ModifiedNode {

  private final boolean myIsNewModel;
  private SModel myModel;
  @NotNull
  private SNodeId myNodeId;
  private List<ModifiedNode> myChildren;
  private ModifiedNode myParent;
  private ModifiedNode myOppositeNode;
  private final ChangeType myType;


  public ModifiedNode(@NotNull SNodeId nodeId, SModel model, ChangeType type, boolean isNew) {
    myModel = model;
    myNodeId = nodeId;
    myType = type;
    myIsNewModel = isNew;
    myChildren = ListSequence.fromList(new ArrayList<ModifiedNode>());
  }

  public ModifiedNode makeCopy() {
    final ModifiedNode copy = new ModifiedNode(myNodeId, myModel, myType, myIsNewModel);
    ListSequence.fromList(myChildren).visitAll(new IVisitor<ModifiedNode>() {
      public void visit(ModifiedNode it) {
        copy.addChild(it);
      }
    });
    copy.setOppositeNode(myOppositeNode);
    copy.setParent(myParent);
    return copy;
  }

  public boolean isMove() {
    return myType == ChangeType.MOVE;
  }

  public void setOppositeNode(ModifiedNode node) {
    myOppositeNode = node;
  }

  public ModifiedNode getOppositeNode() {
    return myOppositeNode;
  }

  public boolean isNew() {
    return myIsNewModel;
  }

  public List<ModifiedNode> getChildren() {
    return myChildren;
  }

  public Set<SNodeId> getAllAffectedNodeIds() {
    final Set<SNodeId> result = SetSequence.fromSet(new HashSet<SNodeId>());
    SetSequence.fromSet(result).addElement(getNodeId());
    ListSequence.fromList(myChildren).visitAll(new IVisitor<ModifiedNode>() {
      public void visit(ModifiedNode it) {
        SetSequence.fromSet(result).addSequence(SetSequence.fromSet(it.getAllAffectedNodeIds()));
      }
    });
    return result;
  }

  public void setParent(ModifiedNode parent) {
    myParent = parent;
  }

  public ModifiedNode getParent() {
    return myParent;
  }

  public void addChild(ModifiedNode child) {
    ListSequence.fromList(myChildren).addElement(child);
  }

  public SNodeId getParentId() {
    return check_vp7k1x_a0a23(getNode().getParent(), this);
  }

  public SNode getNode() {
    return myModel.getNode(myNodeId);
  }

  public SNodeId getNodeId() {
    return myNodeId;
  }

  public SContainmentLink getLink() {
    return SNodeOperations.getContainingLinkInChildrenAndChildAttributesCollection(getNode());
  }

  @NotNull
  public ChangeType getType() {
    return myType;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    if (isMove()) {
      sb.append("moved ");
    } else if (myType == ChangeType.ADD) {
      sb.append("added");
    } else if (myType == ChangeType.DELETE) {
      sb.append("deleted");
    }
    sb.append(check_vp7k1x_a0a2a24(getLink(), this));
    sb.append(" #").append(getNodeId());
    sb.append(" of parent #").append(getParentId());
    return sb.toString();
  }
  private static SNodeId check_vp7k1x_a0a23(SNode checkedDotOperand, ModifiedNode checkedDotThisExpression) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getNodeId();
    }
    return null;
  }
  private static String check_vp7k1x_a0a2a24(SContainmentLink checkedDotOperand, ModifiedNode checkedDotThisExpression) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getName();
    }
    return null;
  }
}
