package jetbrains.mps.kotlin.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IExpression_Constraints extends BaseConstraintsDescriptor {
  public IExpression_Constraints() {
    super(CONCEPTS.IExpression$2i);
  }

  public static class IsVararg_Property extends BasePropertyConstraintsDescriptor {
    public IsVararg_Property(ConstraintsDescriptor container) {
      super(PROPS.isVararg$Z9rG, container, true, false, false);
    }
    @Override
    public Object getValue(SNode node) {
      return false;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.isVararg$Z9rG, new IsVararg_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IExpression$2i = MetaAdapterFactory.getInterfaceConcept(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x28bef6d7551af4d0L, "jetbrains.mps.kotlin.structure.IExpression");
  }

  private static final class PROPS {
    /*package*/ static final SProperty isVararg$Z9rG = MetaAdapterFactory.getProperty(0x6b3888c1980244d8L, 0x8baff8e6c33ed689L, 0x695a62ae1c28f688L, 0x11400bb790b4ef7eL, "isVararg");
  }
}
