package jetbrains.mps.lang.rulesAndMessages.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.feedback.api.MessageDescriptor;
import jetbrains.mps.core.aspects.feedback.api.MessagesAspectDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class GeneratedMessagesAspectDescriptor implements MessagesAspectDescriptor {
  @Nullable
  @Override
  public MessageDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    return null;
  }
}
