package jetbrains.mps.baseLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class DotExpression_SubstituteMenu extends SubstituteMenuBase {
  public DotExpression_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "DotExpression", new SNodePointer("r:00000000-0000-4000-0000-011c895902c3(jetbrains.mps.baseLanguage.editor)", "1741258697586964762")));
  }

}
