package jetbrains.mps.samples.fincalculator.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Command_Constraints extends BaseConstraintsDescriptor {
  public Command_Constraints() {
    super(CONCEPTS.Command$Do);
  }

  @Override
  public SConcept getDefaultConcreteConcept() {
    return CONCEPTS.EmptyLine$CT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Command$Do = MetaAdapterFactory.getConcept(0x26b3d6d5b99a4ed6L, 0x83bed2ea6f3627c2L, 0x1d111c815ef16d50L, "jetbrains.mps.samples.fincalculator.structure.Command");
    /*package*/ static final SConcept EmptyLine$CT = MetaAdapterFactory.getConcept(0x26b3d6d5b99a4ed6L, 0x83bed2ea6f3627c2L, 0x1d111c815ef16d4fL, "jetbrains.mps.samples.fincalculator.structure.EmptyLine");
  }
}
