package jetbrains.mps.baseLanguage.util;

/*Generated by MPS */

import jetbrains.mps.project.facets.JavaLanguageLevel;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.project.facets.JavaModuleFacet;
import org.jetbrains.mps.openapi.module.SModule;

public final class BaseLanguageEnvironmentHelper {

  public JavaLanguageLevel getLanguageLevel(SNode contextNode) {
    return getLanguageLevel(SNodeOperations.getModel(contextNode));
  }
  public JavaLanguageLevel getLanguageLevel(SModel contextModel) {
    return check_sif9ng_a0a2(check_sif9ng_a0a0c(check_sif9ng_a0a0a2(contextModel)));
  }
  private static JavaLanguageLevel check_sif9ng_a0a2(JavaModuleFacet checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getLanguageLevel();
    }
    return null;
  }
  private static JavaModuleFacet check_sif9ng_a0a0c(SModule checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getFacet(JavaModuleFacet.class);
    }
    return null;
  }
  private static SModule check_sif9ng_a0a0a2(SModel checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getModule();
    }
    return null;
  }
}
