package jetbrains.mps.samples.requirementTracking.Traces.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.ConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.annotations.Nullable;

public final class LanguageConceptSwitch implements ConceptIndex {
  private final LanguageConceptIndex myIndex;
  public static final int RequirementEntryReference = 0;
  public static final int RequirementTrace = 1;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x81a3307bd10f4e90L, 0x8043ff6aa5380c33L);
    builder.put(0x39ed36a1ccd6180aL, RequirementEntryReference);
    builder.put(0x39ed36a1ccd3a494L, RequirementTrace);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  @Override
  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }

  @Override
  public int index(@Nullable SAbstractConcept c, int missingValue) {
    return myIndex.index(c, missingValue);
  }
}
