package constraints.rulesAndMessages.sandbox.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.feedback.api.BaseMessageDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.feedback.api.MessageProvider;
import jetbrains.mps.core.aspects.constraints.rules.kinds.CanBeParentContext;
import jetbrains.mps.core.aspects.feedback.api.BaseMessageProvider;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import java.util.Collections;
import java.util.Arrays;

public final class ParentConcept_Messages extends BaseMessageDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xfc39d7264089464aL, 0x8fc15f71edfdf03bL, 0x7af41afae28e1a15L, "constraints.rulesAndMessages.sandbox.structure.ParentConcept");

  private static final MessageProvider<CanBeParentContext> MSGPROVIDER_childIsOfCorrectConcept_737pd2_a = new BaseMessageProvider<CanBeParentContext>(ParentConcept_Constraints2.Rule_childIsOfCorrectConcept.ID_childIsOfCorrectConcept) {
        @NotNull
        @Override
        public MessageProvider.StringMsg yieldMessage(@NotNull CanBeParentContext context) {
          return new MessageProvider.StringMsg("");
        }
  };
  private static final MessageProvider<CanBeParentContext> MSGPROVIDER_propertyIsSetCorrectly_737pd2_b = new BaseMessageProvider<CanBeParentContext>(ParentConcept_Constraints2.Rule_propertyIsSetCorrectly.ID_propertyIsSetCorrectly) {
    @NotNull
    @Override
    public MessageProvider.StringMsg yieldMessage(@NotNull CanBeParentContext context) {
      return new MessageProvider.StringMsg("The prop 'canHaveChildren' is false, so the node" + "' " + String.valueOf(context.getParentNode()) + "' cannot be a parent");
    }
  };
  private static final MessageProvider<CanBeParentContext> MSGPROVIDER_propertyInChildIsSetCorrectly_737pd2_c = new BaseMessageProvider<CanBeParentContext>(ParentConcept_Constraints2.Rule_propertyInChildIsSetCorrectly.ID_propertyInChildIsSetCorrectly) {
    @NotNull
    @Override
    public MessageProvider.StringMsg yieldMessage(@NotNull CanBeParentContext context) {
      return new MessageProvider.StringMsg("The property 'tolerance' is too high" + " in the child node '" + String.valueOf(context.getChildNode()) + "'");
    }
  };

  private static final List<MessageProvider<?>> PROVIDERS = Collections.unmodifiableList(Arrays.<MessageProvider<?>>asList(MSGPROVIDER_childIsOfCorrectConcept_737pd2_a, MSGPROVIDER_propertyIsSetCorrectly_737pd2_b, MSGPROVIDER_propertyInChildIsSetCorrectly_737pd2_c));

  public ParentConcept_Messages() {
    super(CONCEPT);
  }

  @NotNull
  @Override
  public List<MessageProvider<?>> getDeclaredMessageProviders() {
    return PROVIDERS;
  }
}
